In [1]:
import json
from collections import defaultdict
from pathlib import Path

import polars as pl

import src.social_groups.polars_columns as plc
from social_groups.analysis.polars_transformations.apply_parsing_and_group_decision import (
    apply_parsing_and_group_decision,
)
from social_groups.analyzer.io_operations import read_hydra_config
from social_groups.directories import TRACK_FILE_NAME, TRACK_FILE_NAME_COMPRESSED
from social_groups.general.tracking import TrackEntry, iter_jsonl_zst
from social_groups.polars_values import MODEL_NAME_TO_LETTER_MAPPING
from social_groups.reporting.group_reply import (
    GroupReplyAggregator,
    MajorityVote,
)
from social_groups.reporting.parsing import (
    AnswerComparer,
    AnswerOptions,
    AnswerParser,
)
from social_groups.trialrunner.data_connectors.mmlu_pro_subset import (
    MMLUProSubsetConnector,
)
from social_groups.trialrunner.utils.hydra_config import MainConfig

%load_ext autoreload
%autoreload 2

Using Phoenix Cache located at /Users/philipp/Documents/Studium/Informatik/Masterthesis/Repository/results/phoenix/CACHE.

In [2]:
parser = AnswerParser(AnswerOptions.letters_A_to_J)
group_reply = GroupReplyAggregator(MajorityVote())
comparer = AnswerComparer(
    AnswerOptions.letters_A_to_J, triple_underscore_handling="wrong"
)

DIR = Path(
    "/Users/philipp/Documents/Studium/Informatik/Masterthesis/Repository/results/multirun/todo/tribal_council/2026-02-28-16-07-58")

In [3]:
data_connector = MMLUProSubsetConnector()

input_data = pl.DataFrame([p.model_dump() | {"question": data_connector.prepare_example(p).question} for p in
                           data_connector.iterate_data()])

In [4]:
data = defaultdict(list)
info: dict[str, MainConfig] = {}
for i, project_path in enumerate(sorted(DIR.iterdir())):
    if not project_path.is_dir():
        continue
    run_id = i

    run_config = read_hydra_config(project_path)
    info[project_path] = run_config
    # run_meta_info = read_meta_config(project_path)

    if (project_path / TRACK_FILE_NAME_COMPRESSED).exists():

        for item in iter_jsonl_zst(project_path / TRACK_FILE_NAME_COMPRESSED):
            data[project_path].append(TrackEntry.model_validate(item))
    else:
        with (project_path / TRACK_FILE_NAME).open("rb") as f:
            for line in f.readlines():
                data[project_path].append(TrackEntry.model_validate(json.loads(line)))

df = pl.DataFrame(
    [{"question": (x := d.model_dump())["input"]["question"]} | {"project_path": project.name,
                                                                 "num_different_proposals": info[
                                                                     project].experiment.strategy.configuration.num_different_proposals,
                                                                 "council_size": info[
                                                                     project].experiment.strategy.configuration.council_size,
                                                                 "proposal_agent":
                                                                     info[
                                                                         project].experiment.strategy.configuration.proposal_agent.backend.model_name,
                                                                 "council_agent":
                                                                     info[
                                                                         project].experiment.strategy.configuration.council_agent.backend.model_name} | {
         a: b for a, b in
         x["output"].items()}
     for project, datas in data.items() for d in datas],
).drop("used_input_tokens", "used_output_tokens", "final_answer", "history")

In [5]:
tribal_council_results = (
    apply_parsing_and_group_decision(
        df.join(input_data, on="question").drop("src", "category", "cot_content").rename(
            {"answer": "answer_string"}), parser, comparer, group_reply)
).with_columns(pl.col("proposal_agent", "council_agent").replace(MODEL_NAME_TO_LETTER_MAPPING))

In [6]:
tribal_council_results

shape: (3_280, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ question  ┆ project_p ┆ num_diffe ┆ council_s ┆ … ┆ ___parsed ┆ ___parsed ┆ ___parsed ┆ is_corre │
│ ---       ┆ ath       ┆ rent_prop ┆ ize       ┆   ┆ _individu ┆ _combined ┆ _combined ┆ ct       │
│ str       ┆ ---       ┆ osals     ┆ ---       ┆   ┆ al_answer ┆ _answers_ ┆ _answers_ ┆ ---      │
│           ┆ str       ┆ ---       ┆ i64       ┆   ┆ s_a…      ┆ bef…      ┆ aft…      ┆ bool     │
│           ┆           ┆ i64       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q: In     ┆ tribal_co ┆ 2         ┆ 2         ┆ … ┆ ["D",     ┆ ___differ ┆ D         ┆ false    │
│ 2018,     ┆ uncil_0   ┆           ┆           ┆   ┆ "D"]      ┆ ent_votes ┆           ┆          │
│ about how ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ many chi… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q:        ┆ tribal_co ┆ 2         ┆ 2         ┆ … ┆ ["D",     ┆ ___differ ┆ D         ┆ false    │
│ Kirkwood  ┆ uncil_0   ┆           ┆           ┆   ┆ "D"]      ┆ ent_votes ┆           ┆          │
│ gaps are  ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ observed  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q: A 2-mo ┆ tribal_co ┆ 2         ┆ 2         ┆ … ┆ ["A",     ┆ ___differ ┆ A         ┆ false    │
│ nth-old   ┆ uncil_0   ┆           ┆           ┆   ┆ "A"]      ┆ ent_votes ┆           ┆          │
│ female is ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ bro…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q: A      ┆ tribal_co ┆ 2         ┆ 2         ┆ … ┆ ["A",     ┆ ___differ ┆ A         ┆ false    │
│ wealthy   ┆ uncil_0   ┆           ┆           ┆   ┆ "A"]      ┆ ent_votes ┆           ┆          │
│ woman     ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ often     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ wore …    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q: What   ┆ tribal_co ┆ 2         ┆ 2         ┆ … ┆ ["J",     ┆ ___differ ┆ J         ┆ true     │
│ stable    ┆ uncil_0   ┆           ┆           ┆   ┆ "J"]      ┆ ent_votes ┆           ┆          │
│ isotope   ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ is comm…  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Q: In a   ┆ tribal_co ┆ 2         ┆ 3         ┆ … ┆ []        ┆ A         ┆ ___all_vo ┆ false    │
│ given     ┆ uncil_9   ┆           ┆           ┆   ┆           ┆           ┆ tes_inval ┆          │
│ economy,  ┆           ┆           ┆           ┆   ┆           ┆           ┆ id___     ┆          │
│ househo…  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q: Camera ┆ tribal_co ┆ 2         ┆ 3         ┆ … ┆ ["F",     ┆ ___differ ┆ F         ┆ false    │
│ lenses    ┆ uncil_9   ┆           ┆           ┆   ┆ "F", "F"] ┆ ent_votes ┆           ┆          │
│ usually   ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ conta…    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q: Of the ┆ tribal_co ┆ 2         ┆ 3         ┆ … ┆ ["D",     ┆ ___differ ┆ D         ┆ false    │
│ following ┆ uncil_9   ┆           ┆           ┆   ┆ "D", "D"] ┆ ent_votes ┆           ┆          │
│ , the     ┆           ┆           ┆           ┆   ┆           ┆ ___       ┆           ┆          │
│ best …    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q: Mrs.   ┆ tribal_co ┆ 2         ┆ 3         ┆ … ┆ []        ┆ A         ┆ ___all_vo ┆ false    │
│ Reynolds  ┆ uncil_9   ┆           ┆           ┆   ┆           ┆           ┆ tes_inval ┆          │
│ purchased ┆           ┆           ┆           ┆   ┆           ┆           ┆ id___     ┆          │
│ $45…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q:        ┆ tribal_co ┆ 2         ┆ 3         ┆ … ┆ []        ┆ H         ┆ ___all_vo ┆ false    │
│ Determine ┆ uncil_9   ┆           ┆           ┆   ┆           ┆           ┆ tes_inval ┆          │
│ the multi ┆           ┆           ┆           ┆   ┆           ┆           ┆ id___     ┆          │
│ plicity … ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
tribal_council_results.group_by("project_path", "num_different_proposals", "council_size", "proposal_agent",
                                "council_agent").agg(
    pl.col(plc.is_correct).mean().alias(plc.accuracy), available_data=pl.len() / 100).sort("accuracy", descending=True)

shape: (36, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────────┬──────────┬─────────────┐
│ project_path ┆ num_differen ┆ council_size ┆ proposal_age ┆ council_age ┆ accuracy ┆ available_d │
│ ---          ┆ t_proposals  ┆ ---          ┆ nt           ┆ nt          ┆ ---      ┆ ata         │
│ str          ┆ ---          ┆ i64          ┆ ---          ┆ ---         ┆ f64      ┆ ---         │
│              ┆ i64          ┆              ┆ str          ┆ str         ┆          ┆ f64         │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════════╪══════════╪═════════════╡
│ tribal_counc ┆ 2            ┆ 3            ┆ H            ┆ L           ┆ 0.73     ┆ 1.0         │
│ il_15        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 3            ┆ 3            ┆ H            ┆ H           ┆ 0.714286 ┆ 0.21        │
│ il_35        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 2            ┆ 2            ┆ H            ┆ M           ┆ 0.71     ┆ 1.0         │
│ il_7         ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 3            ┆ 2            ┆ H            ┆ H           ┆ 0.69697  ┆ 0.66        │
│ il_26        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 2            ┆ 2            ┆ H            ┆ H           ┆ 0.69     ┆ 1.0         │
│ il_8         ┆              ┆              ┆              ┆             ┆          ┆             │
│ …            ┆ …            ┆ …            ┆ …            ┆ …           ┆ …        ┆ …           │
│ tribal_counc ┆ 3            ┆ 3            ┆ L            ┆ H           ┆ 0.29     ┆ 1.0         │
│ il_29        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 3            ┆ 2            ┆ L            ┆ M           ┆ 0.28     ┆ 1.0         │
│ il_19        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 3            ┆ 2            ┆ L            ┆ H           ┆ 0.28     ┆ 1.0         │
│ il_20        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 3            ┆ 3            ┆ L            ┆ M           ┆ 0.27     ┆ 1.0         │
│ il_28        ┆              ┆              ┆              ┆             ┆          ┆             │
│ tribal_counc ┆ 3            ┆ 2            ┆ L            ┆ L           ┆ 0.24     ┆ 1.0         │
│ il_18        ┆              ┆              ┆              ┆             ┆          ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────────┴──────────┴─────────────┘

In [8]:
data[Path(
    '/Users/philipp/Documents/Studium/Informatik/Masterthesis/Repository/results/multirun/todo/tribal_council/2026-02-28-16-07-58/tribal_council_35')][
    0].phoenix_span_info

PhoenixExampleHandle(trace_id_hex='45b83f1e1b5928202295ca2edbb5d68a', span_id_hex='04392656cf7083f0', captured_span_ids=['04392656cf7083f0', 'b68b7597088278b2', 'dca257fa52977cea', '3426f2e8898f4412', '8006663f57dc7c0c', '6b88fc8106fd0842', 'f6830e602b3f2d4b', 'acb6250a8b0998a0', '8086fbe3d62d5a0f', '0ec62d2c18545575', '79f3d21c456dbf9e', '3d43e2528b69afdc', 'bb1350d578545c3a', '1bd7edecfb209e11', '6c0f49fb22470177', 'b1bd078ed1b9fff1', '58ae49a354d1aad3', 'd14497bf79348ea3', 'd1f00033b3251395', '91b2bc8d0de3f193', 'f13f0426d6f6b117', '985f8c8dcb1e09fe', 'b0af017c8561916a', '348ac362c79d29ee', '313d16f3d018d275', 'fbd3075a87db825c', 'ac9a2fbaea23e86d', '81531721211d62b0', '52bc7360a96bc5c9', 'ae53d082643633ea', 'ebd0777fc910688c', '935e888563d30a3f', 'e535797bd367aa2a', '55f55c5c1552679e', '7697d9dc436f13b6', '0c928f2a06ec8fa3', 'd2bf3219360fe2c4', '29c69d38aba76d00', '933b89aaa9fd10b0', '8a303cf0ff3dc8e0', '978f9669b0c75fbd', '2ec37af67c9d450a'])

In [9]:
# from social_groups.analyzer.utils import get_span_attributes

# get_span_attributes(span_ids=['04392656cf7083f0'], phoenix_graphql_endpoint="http://localhost:6006/graphql")

In [10]:
from social_groups.reporting.analysis_columns import AnalysisColumn
from social_groups.reporting.group_decision_scheme import calculate_decision_scheme

for group in tribal_council_results.group_by("project_path", "num_different_proposals", "council_size",
                                             "proposal_agent",
                                             "council_agent"):
    print(group[0], "available data: ", group[1].shape[0])
    print(calculate_decision_scheme(
        group[1],
        AnalysisColumn.parsed_individual_answers_before.value,
        AnalysisColumn.parsed_individual_answers_after.value,
        "answer_string",
        group_reply,
        comparer,
    ).select("Correct Members Beginning", "correct", "incorrect"))

('tribal_council_3', 2, 2, 'M', 'L') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.961538 ┆ 0.038462  │
│ 1                         ┆ 0.75     ┆ 0.25      │
│ 0                         ┆ 0.03125  ┆ 0.96875   │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_9', 2, 3, 'L', 'L') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.95     ┆ 0.05      │
│ 1                         ┆ 0.393939 ┆ 0.606061  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_23', 3, 2, 'M', 'H') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.9375   ┆ 0.0625    │
│ 2                         ┆ 0.555556 ┆ 0.444444  │
│ 1                         ┆ 0.421053 ┆ 0.578947  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_22', 3, 2, 'M', 'M') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.857143 ┆ 0.142857  │
│ 2                         ┆ 0.666667 ┆ 0.333333  │
│ 1                         ┆ 0.333333 ┆ 0.666667  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_2', 2, 2, 'L', 'H') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.882353 ┆ 0.117647  │
│ 1                         ┆ 0.484848 ┆ 0.515152  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_26', 3, 2, 'H', 'H') available data:  66
shape: (4, 3)
┌───────────────────────────┬─────────┬───────────┐
│ Correct Members Beginning ┆ correct ┆ incorrect │
│ ---                       ┆ ---     ┆ ---       │
│ u32                       ┆ f64     ┆ f64       │
╞═══════════════════════════╪═════════╪═══════════╡
│ 3                         ┆ 1.0     ┆ 0.0       │
│ 2                         ┆ 0.75    ┆ 0.25      │
│ 1                         ┆ 0.5     ┆ 0.5       │
│ 0                         ┆ 0.0     ┆ 1.0       │
└───────────────────────────┴─────────┴───────────┘
('tribal_council_8', 2, 2, 'H', 'H') available data:  100
shape: (3, 3)
┌───────────────────────────┬─────────┬───────────┐
│ Correct Members Beginning ┆ correct ┆ incorrect │
│ ---                       ┆ ---     ┆ ---       │
│ u32                       ┆ f64     ┆ f64       │
╞═══════════════════════════╪═════════╪═══════════╡
│ 2                         ┆ 1.0     ┆ 0.0       │
│ 1                         ┆ 0.5     ┆ 0.5       │
│ 0                         ┆ 0.12    ┆ 0.88      │
└───────────────────────────┴─────────┴───────────┘
('tribal_council_33', 3, 3, 'H', 'L') available data:  22
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.6      ┆ 0.4       │
│ 1                         ┆ 0.666667 ┆ 0.333333  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_32', 3, 3, 'M', 'H') available data:  63
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.967742 ┆ 0.032258  │
│ 2                         ┆ 0.666667 ┆ 0.333333  │
│ 1                         ┆ 0.555556 ┆ 0.444444  │
│ 0                         ┆ 0.05     ┆ 0.95      │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_25', 3, 2, 'H', 'M') available data:  88
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.978261 ┆ 0.021739  │
│ 2                         ┆ 0.5      ┆ 0.5       │
│ 1                         ┆ 0.5      ┆ 0.5       │
│ 0                         ┆ 0.05     ┆ 0.95      │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_10', 2, 3, 'L', 'M') available data:  100
shape: (3, 3)
┌───────────────────────────┬─────────┬───────────┐
│ Correct Members Beginning ┆ correct ┆ incorrect │
│ ---                       ┆ ---     ┆ ---       │
│ u32                       ┆ f64     ┆ f64       │
╞═══════════════════════════╪═════════╪═══════════╡
│ 2                         ┆ 1.0     ┆ 0.0       │
│ 1                         ┆ 0.40625 ┆ 0.59375   │
│ 0                         ┆ 0.0     ┆ 1.0       │
└───────────────────────────┴─────────┴───────────┘
('tribal_council_27', 3, 3, 'L', 'L') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.7      ┆ 0.3       │
│ 1                         ┆ 0.366667 ┆ 0.633333  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_34', 3, 3, 'H', 'M') available data:  22
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.5      ┆ 0.5       │
│ 1                         ┆ 0.5      ┆ 0.5       │
│ 0                         ┆ 0.166667 ┆ 0.833333  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_15', 2, 3, 'H', 'L') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 1.0      ┆ 0.0       │
│ 1                         ┆ 0.619048 ┆ 0.380952  │
│ 0                         ┆ 0.136364 ┆ 0.863636  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_19', 3, 2, 'L', 'M') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.8      ┆ 0.2       │
│ 2                         ┆ 0.777778 ┆ 0.222222  │
│ 1                         ┆ 0.264706 ┆ 0.735294  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_28', 3, 3, 'L', 'M') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.636364 ┆ 0.363636  │
│ 1                         ┆ 0.25     ┆ 0.75      │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_0', 2, 2, 'L', 'L') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.833333 ┆ 0.166667  │
│ 1                         ┆ 0.583333 ┆ 0.416667  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_31', 3, 3, 'M', 'M') available data:  98
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.914894 ┆ 0.085106  │
│ 2                         ┆ 0.6      ┆ 0.4       │
│ 1                         ┆ 0.444444 ┆ 0.555556  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_14', 2, 3, 'M', 'H') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.921569 ┆ 0.078431  │
│ 1                         ┆ 0.538462 ┆ 0.461538  │
│ 0                         ┆ 0.027778 ┆ 0.972222  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_5', 2, 2, 'M', 'H') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 1.0      ┆ 0.0       │
│ 1                         ┆ 0.333333 ┆ 0.666667  │
│ 0                         ┆ 0.090909 ┆ 0.909091  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_18', 3, 2, 'L', 'L') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.727273 ┆ 0.272727  │
│ 1                         ┆ 0.058824 ┆ 0.941176  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_35', 3, 3, 'H', 'H') available data:  21
shape: (4, 3)
┌───────────────────────────┬─────────┬───────────┐
│ Correct Members Beginning ┆ correct ┆ incorrect │
│ ---                       ┆ ---     ┆ ---       │
│ u32                       ┆ f64     ┆ f64       │
╞═══════════════════════════╪═════════╪═══════════╡
│ 3                         ┆ 1.0     ┆ 0.0       │
│ 2                         ┆ 1.0     ┆ 0.0       │
│ 1                         ┆ 0.5     ┆ 0.5       │
│ 0                         ┆ 0.2     ┆ 0.8       │
└───────────────────────────┴─────────┴───────────┘
('tribal_council_21', 3, 2, 'M', 'L') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.938776 ┆ 0.061224  │
│ 2                         ┆ 0.5      ┆ 0.5       │
│ 1                         ┆ 0.333333 ┆ 0.666667  │
│ 0                         ┆ 0.033333 ┆ 0.966667  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_20', 3, 2, 'L', 'H') available data:  100
shape: (4, 3)
┌───────────────────────────┬─────────┬───────────┐
│ Correct Members Beginning ┆ correct ┆ incorrect │
│ ---                       ┆ ---     ┆ ---       │
│ u32                       ┆ f64     ┆ f64       │
╞═══════════════════════════╪═════════╪═══════════╡
│ 3                         ┆ 0.875   ┆ 0.125     │
│ 2                         ┆ 0.625   ┆ 0.375     │
│ 1                         ┆ 0.28125 ┆ 0.71875   │
│ 0                         ┆ 0.0     ┆ 1.0       │
└───────────────────────────┴─────────┴───────────┘
('tribal_council_1', 2, 2, 'L', 'M') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.866667 ┆ 0.133333  │
│ 1                         ┆ 0.515152 ┆ 0.484848  │
│ 0                         ┆ 0.019231 ┆ 0.980769  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_17', 2, 3, 'H', 'H') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.982759 ┆ 0.017241  │
│ 1                         ┆ 0.588235 ┆ 0.411765  │
│ 0                         ┆ 0.04     ┆ 0.96      │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_13', 2, 3, 'M', 'M') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 1.0      ┆ 0.0       │
│ 1                         ┆ 0.388889 ┆ 0.611111  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_4', 2, 2, 'M', 'M') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.921569 ┆ 0.078431  │
│ 1                         ┆ 0.388889 ┆ 0.611111  │
│ 0                         ┆ 0.064516 ┆ 0.935484  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_16', 2, 3, 'H', 'M') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 1.0      ┆ 0.0       │
│ 1                         ┆ 0.428571 ┆ 0.571429  │
│ 0                         ┆ 0.045455 ┆ 0.954545  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_12', 2, 3, 'M', 'L') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.918367 ┆ 0.081633  │
│ 1                         ┆ 0.315789 ┆ 0.684211  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_7', 2, 2, 'H', 'M') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 1.0      ┆ 0.0       │
│ 1                         ┆ 0.619048 ┆ 0.380952  │
│ 0                         ┆ 0.045455 ┆ 0.954545  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_11', 2, 3, 'L', 'H') available data:  100
shape: (3, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 2                         ┆ 0.9      ┆ 0.1       │
│ 1                         ┆ 0.419355 ┆ 0.580645  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_29', 3, 3, 'L', 'H') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.727273 ┆ 0.272727  │
│ 1                         ┆ 0.185185 ┆ 0.814815  │
│ 0                         ┆ 0.0      ┆ 1.0       │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_30', 3, 3, 'M', 'L') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 0.979592 ┆ 0.020408  │
│ 2                         ┆ 1.0      ┆ 0.0       │
│ 1                         ┆ 0.315789 ┆ 0.684211  │
│ 0                         ┆ 0.034483 ┆ 0.965517  │
└───────────────────────────┴──────────┴───────────┘
('tribal_council_24', 3, 2, 'H', 'L') available data:  100
shape: (4, 3)
┌───────────────────────────┬──────────┬───────────┐
│ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                       ┆ ---      ┆ ---       │
│ u32                       ┆ f64      ┆ f64       │
╞═══════════════════════════╪══════════╪═══════════╡
│ 3                         ┆ 1.0      ┆ 0.0       │
│ 2                         ┆ 0.692308 ┆ 0.307692  │

In [11]:
COUNCIL_NUMBER = 15

In [12]:
from social_groups.reporting.group_decision_scheme import (
    calculate_extended_decision_scheme,
)

dec_scheme = calculate_extended_decision_scheme(
    tribal_council_results.filter(pl.col("project_path") == f"tribal_council_{COUNCIL_NUMBER}"),
    AnalysisColumn.parsed_individual_answers_before.value,
    AnalysisColumn.parsed_individual_answers_after.value,
    "answer_string",
    group_reply,
    comparer,
)
dec_scheme

shape: (5, 5)
┌───────────────────────────┬─────────────────────┬─────────┬─────────────┬───────────┐
│ Correct Members Beginning ┆ Correct Members End ┆ correct ┆ occurrences ┆ incorrect │
│ ---                       ┆ ---                 ┆ ---     ┆ ---         ┆ ---       │
│ u32                       ┆ u32                 ┆ f64     ┆ u32         ┆ f64       │
╞═══════════════════════════╪═════════════════════╪═════════╪═════════════╪═══════════╡
│ 2                         ┆ 3                   ┆ 1.0     ┆ 57          ┆ 0.0       │
│ 1                         ┆ 3                   ┆ 1.0     ┆ 13          ┆ 0.0       │
│ 1                         ┆ 0                   ┆ 0.0     ┆ 8           ┆ 1.0       │
│ 0                         ┆ 3                   ┆ 1.0     ┆ 3           ┆ 0.0       │
│ 0                         ┆ 0                   ┆ 0.0     ┆ 19          ┆ 1.0       │
└───────────────────────────┴─────────────────────┴─────────┴─────────────┴───────────┘

In [13]:
from social_groups.reporting.plots.decision_scheme_extended import (
    make_decision_scheme_extended_plot,
)

make_decision_scheme_extended_plot(
    dec_scheme, title=f"Group {COUNCIL_NUMBER}"
).show(width=800, height=600)

In [14]:
all_cases = list(
    sorted(
        set(dec_scheme["Correct Members Beginning"].unique()).union(
            set(dec_scheme["Correct Members End"].unique())
        )
    )
)

all_cases

[0, 1, 2, 3]

In [15]:
left_groups = [f" {x}☑ (Start)" for x in all_cases]
right_groups = [f" {x}☑ (End)" for x in all_cases]
left_groups, right_groups

([' 0☑ (Start)', ' 1☑ (Start)', ' 2☑ (Start)', ' 3☑ (Start)'],
 [' 0☑ (End)', ' 1☑ (End)', ' 2☑ (End)', ' 3☑ (End)'])

In [16]:
dec_scheme

shape: (5, 5)
┌───────────────────────────┬─────────────────────┬─────────┬─────────────┬───────────┐
│ Correct Members Beginning ┆ Correct Members End ┆ correct ┆ occurrences ┆ incorrect │
│ ---                       ┆ ---                 ┆ ---     ┆ ---         ┆ ---       │
│ u32                       ┆ u32                 ┆ f64     ┆ u32         ┆ f64       │
╞═══════════════════════════╪═════════════════════╪═════════╪═════════════╪═══════════╡
│ 2                         ┆ 3                   ┆ 1.0     ┆ 57          ┆ 0.0       │
│ 1                         ┆ 3                   ┆ 1.0     ┆ 13          ┆ 0.0       │
│ 1                         ┆ 0                   ┆ 0.0     ┆ 8           ┆ 1.0       │
│ 0                         ┆ 3                   ┆ 1.0     ┆ 3           ┆ 0.0       │
│ 0                         ┆ 0                   ┆ 0.0     ┆ 19          ┆ 1.0       │
└───────────────────────────┴─────────────────────┴─────────┴─────────────┴───────────┘

In [17]:
correct_at_end_given_correct_start_members = (
    pl.DataFrame({"Correct Members Beginning": all_cases})
    .join(
        dec_scheme.group_by("Correct Members Beginning")
        .agg(
            correct=(
                    pl.col("correct").dot(pl.col("occurrences")) / pl.sum("occurrences")
            ).mean()
        )
        .select("correct", "Correct Members Beginning"),
        on="Correct Members Beginning",
        how="left",
    )
    .with_columns(pl.col("correct").fill_null(0))
    .sort("Correct Members Beginning", descending=True)
    .select("correct")
    .to_numpy()
    .reshape(len(right_groups), 1)
)

correct_at_end_given_correct_start_members

array([[0.        ],
       [1.        ],
       [0.61904762],
       [0.13636364]])

In [18]:
dec_scheme.select(
    "Correct Members Beginning", "Correct Members End", "occurrences"
)

shape: (5, 3)
┌───────────────────────────┬─────────────────────┬─────────────┐
│ Correct Members Beginning ┆ Correct Members End ┆ occurrences │
│ ---                       ┆ ---                 ┆ ---         │
│ u32                       ┆ u32                 ┆ u32         │
╞═══════════════════════════╪═════════════════════╪═════════════╡
│ 2                         ┆ 3                   ┆ 57          │
│ 1                         ┆ 3                   ┆ 13          │
│ 1                         ┆ 0                   ┆ 8           │
│ 0                         ┆ 3                   ┆ 3           │
│ 0                         ┆ 0                   ┆ 19          │
└───────────────────────────┴─────────────────────┴─────────────┘

In [19]:
dec_scheme.schema

Schema([('Correct Members Beginning', UInt32),
        ('Correct Members End', UInt32),
        ('correct', Float64),
        ('occurrences', UInt32),
        ('incorrect', Float64)])

In [20]:
from itertools import repeat
import numpy as np

links = (
    pl.DataFrame({"Correct Members Beginning": list(y for x in repeat(all_cases, len(all_cases)) for y in x),
                  "Correct Members End": [y for x in all_cases for y in repeat(x, len(all_cases))]},
                 schema={"Correct Members Beginning": pl.datatypes.UInt32, "Correct Members End": pl.datatypes.UInt32})
    .join(
        dec_scheme,
        on=["Correct Members Beginning", "Correct Members End"],
        how="left",
    ).with_columns(pl.col("occurrences").fill_null(0))
    .select(
        "Correct Members Beginning", "Correct Members End", "occurrences"
    ).map_rows(lambda r: np.array(r))["map"]
    .to_list()
)

links

[[0, 0, 19],
 [1, 0, 8],
 [2, 0, 0],
 [3, 0, 0],
 [0, 1, 0],
 [1, 1, 0],
 [2, 1, 0],
 [3, 1, 0],
 [0, 2, 0],
 [1, 2, 0],
 [2, 2, 0],
 [3, 2, 0],
 [0, 3, 3],
 [1, 3, 13],
 [2, 3, 57],
 [3, 3, 0]]

In [21]:
nL = len(left_groups)
nL

4

In [22]:
source = [s for s, t, v in links]
target = [nL + t for s, t, v in links]
value = [v for s, t, v in links]

In [23]:
source, target, value

([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
 [4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7],
 [19, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 13, 57, 0])

In [24]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from pyfonts import load_google_font


def hex_to_rgba(hex_color, a=0.22):
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r},{g},{b},{a})"


make_subplots(
    rows=1,
    cols=3,
    column_widths=[0.4, 2, 0.4],
    specs=[[{"type": "heatmap"}, {"type": "sankey"}, {"type": "heatmap"}]],
    horizontal_spacing=0.01,
    subplot_titles=[
        "Correct Group Dec.<br> (p. No. corr. @ start)",
        "TITLE" + "<br> ",
        "",
    ],
).add_trace(
    go.Sankey(
        arrangement="snap",
        node=dict(
            label=left_groups + right_groups,
            pad=20,
            thickness=16,
            color=["#A3B1C6", "#B9A3C9", "#323647", "#D4A35C", "#6C7A89"],
            line=dict(color="rgba(0,0,0,0.3)", width=0.6),
            # Change the order ot the nodes ...
            x=[0.01 for _ in left_groups] + [0.99 for _ in right_groups],
            y=np.cumsum([0.17 for _ in left_groups]).tolist()[::-1] * 2,
        ),
        link=dict(
            source=source,
            target=target,
            value=value,
            color=[hex_to_rgba(["#A3B1C6", "#B9A3C9", "#323647", "#D4A35C", "#6C7A89"][s], 0.22) for s in source],
        ),
        textfont=dict(
            family=load_google_font("Libre Baskerville", weight="bold").get_name(),
            size=12,
            color="rgb(34,32,32)",
            shadow="none",
        ),
    ),
    row=1,
    col=2,
)