In [62]:
import os
from collections import defaultdict
from itertools import chain

import polars as pl

from social_groups.reporting.analysis_columns import AnalysisColumn
from social_groups.reporting.group_reply import (
    GroupReplyAggregator,
    MajorityVote,
    SingularityVote,
)
from social_groups.reporting.parsing import (
    AnswerOptions,
    AnswerParser,
    AnswerComparer,
)
from social_groups.directories import REPORTING_DIR
from social_groups.reporting.plots.config import MODEL_NAME_TO_LETTER_MAPPING
from social_groups.reporting.group_decision_scheme import calculate_decision_scheme

from social_groups.reporting.heterogenous_comparison.data_retrieval import (
    get_baseline_frame,
    get_mad_frame,
    apply_parsing_and_group_decision,
)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [63]:
output_dir = REPORTING_DIR / "heterogeneous_group"
os.makedirs(output_dir, exist_ok=True)

triple_underscore_handling = "random"

In [64]:
parser = AnswerParser(AnswerOptions.letters_A_to_J)
group_reply = GroupReplyAggregator(MajorityVote())
comparer = AnswerComparer(
    AnswerOptions.letters_A_to_J, triple_underscore_handling="random"
)

In [65]:
baseline_frame = get_baseline_frame()

In [66]:
baseline_frame

shape: (300, 12)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ run_id ┆ question_id ┆ phoenix_spa ┆ … ┆ category   ┆ question   ┆ answer_str ┆ model_name │
│ --- ┆ ---    ┆ ---         ┆ n_id        ┆   ┆ ---        ┆ ---        ┆ ing        ┆ ---        │
│ i64 ┆ i64    ┆ i64         ┆ ---         ┆   ┆ str        ┆ str        ┆ ---        ┆ str        │
│     ┆        ┆             ┆ str         ┆   ┆            ┆            ┆ str        ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0   ┆ 0      ┆ 0           ┆ c9ce50b76ff ┆ … ┆ health     ┆ Q: What    ┆ J          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ e168f       ┆   ┆            ┆ stable     ┆            ┆ -4B        │
│     ┆        ┆             ┆             ┆   ┆            ┆ isotope is ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ comm…      ┆            ┆            │
│ 1   ┆ 0      ┆ 1           ┆ 87b17edffe4 ┆ … ┆ law        ┆ Q: A       ┆ E          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ 75e00       ┆   ┆            ┆ company    ┆            ┆ -4B        │
│     ┆        ┆             ┆             ┆   ┆            ┆ contracted ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ with a…    ┆            ┆            │
│ 2   ┆ 0      ┆ 2           ┆ fc4fba7e319 ┆ … ┆ physics    ┆ Q: An      ┆ I          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ 96dbd       ┆   ┆            ┆ electric   ┆            ┆ -4B        │
│     ┆        ┆             ┆             ┆   ┆            ┆ dipole     ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ consisti…  ┆            ┆            │
│ 3   ┆ 0      ┆ 3           ┆ a07b8366a72 ┆ … ┆ other      ┆ Q: In      ┆ G          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ 8060b       ┆   ┆            ┆ 2018,      ┆            ┆ -4B        │
│     ┆        ┆             ┆             ┆   ┆            ┆ about how  ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ many chi…  ┆            ┆            │
│ 4   ┆ 0      ┆ 4           ┆ 0d68cb744ba ┆ … ┆ law        ┆ Q: A       ┆ E          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ d1f9c       ┆   ┆            ┆ wealthy    ┆            ┆ -4B        │
│     ┆        ┆             ┆             ┆   ┆            ┆ woman      ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ often wore ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ …          ┆            ┆            │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 335 ┆ 2      ┆ 98          ┆ 161a98855c2 ┆ … ┆ economics  ┆ Q: Which   ┆ F          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ 5244f       ┆   ┆            ┆ of the     ┆            ┆ -14B       │
│     ┆        ┆             ┆             ┆   ┆            ┆ following  ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ exam…      ┆            ┆            │
│ 336 ┆ 2      ┆ 59          ┆ 286db26b7a2 ┆ … ┆ economics  ┆ Q: In the  ┆ B          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ 629e7       ┆   ┆            ┆ extreme    ┆            ┆ -14B       │
│     ┆        ┆             ┆             ┆   ┆            ┆ case, $    ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ 1,00…      ┆            ┆            │
│ 337 ┆ 2      ┆ 58          ┆ 394fd48a69e ┆ … ┆ psychology ┆ Q:         ┆ F          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ f5655       ┆   ┆            ┆ Describe   ┆            ┆ -14B       │
│     ┆        ┆             ┆             ┆   ┆            ┆ Sherman's  ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ and Key'…  ┆            ┆            │
│ 338 ┆ 2      ┆ 99          ┆ 5f50118d4ad ┆ … ┆ economics  ┆ Q: What    ┆ G          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ efb50       ┆   ┆            ┆ would the  ┆            ┆ -14B       │
│     ┆        ┆             ┆             ┆   ┆            ┆ money rate ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ o…         ┆            ┆            │
│ 339 ┆ 2      ┆ 13          ┆ 2e911020ad5 ┆ … ┆ economics  ┆ Q: With    ┆ D          ┆ Qwen/Qwen3 │
│     ┆        ┆             ┆ 92f30       ┆   ┆            ┆ respect to ┆            ┆ -14B       │
│     ┆        ┆             ┆             ┆   ┆            ┆ the kinked ┆            ┆            │
│     ┆        ┆             ┆             ┆   ┆            ┆ …          ┆            ┆            │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [67]:
print("Number of unparsable answers:")
print(
    baseline_frame.with_columns(
        parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
    )
    .group_by("model_name")
    .agg(
        no_null=pl.col(AnalysisColumn.parsed_answer.value)
        .str.starts_with("___")
        .not_()
        .sum(),
        null_percentage=(
            pl.col(AnalysisColumn.parsed_answer.value).str.starts_with("___").mean()
            * 100
        ).round(2),
    )
    .sort(pl.col("model_name").str.extract(r"-(\d+\.?\d*)B", 1).cast(pl.Float64))
)

baseline_analysis = (
    baseline_frame.with_columns(
        parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
    )
    .with_columns(
        is_correct=comparer(
            pl.col(AnalysisColumn.parsed_answer.value), pl.col("answer_string")
        )
    )
    .group_by("model_name")
    .agg(accuracy=pl.col("is_correct").mean())
    .sort(pl.col("model_name").str.extract(r"-(\d+\.?\d*)B", 1).cast(pl.Float64))
)

baseline_analysis

Number of unparsable answers:
shape: (3, 3)
┌─────────────────┬─────────┬─────────────────┐
│ model_name      ┆ no_null ┆ null_percentage │
│ ---             ┆ ---     ┆ ---             │
│ str             ┆ u32     ┆ f64             │
╞═════════════════╪═════════╪═════════════════╡
│ Qwen/Qwen3-0.6B ┆ 90      ┆ 10.0            │
│ Qwen/Qwen3-4B   ┆ 88      ┆ 12.0            │
│ Qwen/Qwen3-14B  ┆ 93      ┆ 7.0             │
└─────────────────┴─────────┴─────────────────┘

shape: (3, 2)
┌─────────────────┬──────────┐
│ model_name      ┆ accuracy │
│ ---             ┆ ---      │
│ str             ┆ f64      │
╞═════════════════╪══════════╡
│ Qwen/Qwen3-0.6B ┆ 0.37     │
│ Qwen/Qwen3-4B   ┆ 0.6      │
│ Qwen/Qwen3-14B  ┆ 0.65     │
└─────────────────┴──────────┘

## Analzying Basic Group Behaviour

In [68]:
mad_frame = get_mad_frame()
mad_frame

shape: (1_900, 17)
┌──────┬────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id   ┆ run_id ┆ question_id ┆ phoenix_sp ┆ … ┆ category   ┆ question   ┆ answer_str ┆ model_name │
│ ---  ┆ ---    ┆ ---         ┆ an_id      ┆   ┆ ---        ┆ ---        ┆ ing        ┆ s          │
│ i64  ┆ i64    ┆ i64         ┆ ---        ┆   ┆ str        ┆ str        ┆ ---        ┆ ---        │
│      ┆        ┆             ┆ str        ┆   ┆            ┆            ┆ str        ┆ list[str]  │
╞══════╪════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 230  ┆ 3      ┆ 63          ┆ bf94cefe4f ┆ … ┆ philosophy ┆ Q: The     ┆ C          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 7d6a67     ┆   ┆            ┆ theory     ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆            ┆   ┆            ┆ that says  ┆            ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ mental…    ┆            ┆            │
│ 231  ┆ 3      ┆ 6           ┆ 997b3806bf ┆ … ┆ computer   ┆ Q: In      ┆ C          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ b3898e     ┆   ┆ science    ┆ building a ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆            ┆   ┆            ┆ linear     ┆            ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ regres…    ┆            ┆            │
│ 238  ┆ 3      ┆ 41          ┆ 17efe8d5fd ┆ … ┆ math       ┆ Q: Pat     ┆ I          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 7b7069     ┆   ┆            ┆ bounces a  ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆            ┆   ┆            ┆ basketball ┆            ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ 25…        ┆            ┆            │
│ 239  ┆ 3      ┆ 105         ┆ 1ab4b05cf3 ┆ … ┆ other      ┆ Q: Which   ┆ I          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 0bf020     ┆   ┆            ┆ of the     ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆            ┆   ┆            ┆ following  ┆            ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ list…      ┆            ┆            │
│ 248  ┆ 3      ┆ 8           ┆ c385b50db1 ┆ … ┆ chemistry  ┆ Q: A       ┆ E          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 39472a     ┆   ┆            ┆ sample of  ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆            ┆   ┆            ┆ bristle    ┆            ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ cone pi…   ┆            ┆            │
│ …    ┆ …      ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2195 ┆ 21     ┆ 10          ┆ c21a7361cd ┆ … ┆ physics    ┆ Q: X rays  ┆ J          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ d9e460     ┆   ┆            ┆ scattered  ┆            ┆ n3-0.6B",  │
│      ┆        ┆             ┆            ┆   ┆            ┆ from rock  ┆            ┆ "Qwen/Qwen │
│      ┆        ┆             ┆            ┆   ┆            ┆ …          ┆            ┆ …          │
│ 2196 ┆ 21     ┆ 14          ┆ 95c6302a0f ┆ … ┆ math       ┆ Q: John    ┆ H          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 46a9fb     ┆   ┆            ┆ noticed    ┆            ┆ n3-0.6B",  │
│      ┆        ┆             ┆            ┆   ┆            ┆ that the   ┆            ┆ "Qwen/Qwen │
│      ┆        ┆             ┆            ┆   ┆            ┆ angle…     ┆            ┆ …          │
│ 2197 ┆ 21     ┆ 45          ┆ 6228e2254e ┆ … ┆ law        ┆ Q: A busin ┆ B          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ f5fcda     ┆   ┆            ┆ essman is  ┆            ┆ n3-0.6B",  │
│      ┆        ┆             ┆            ┆   ┆            ┆ the owner  ┆            ┆ "Qwen/Qwen │
│      ┆        ┆             ┆            ┆   ┆            ┆ …          ┆            ┆ …          │
│ 2198 ┆ 21     ┆ 43          ┆ 2d8bf17996 ┆ … ┆ math       ┆ Q: Gwen    ┆ H          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ c57d3a     ┆   ┆            ┆ wrote the  ┆            ┆ n3-0.6B",  │
│      ┆        ┆             ┆            ┆   ┆            ┆ number     ┆            ┆ "Qwen/Qwen │
│      ┆        ┆             ┆            ┆   ┆            ┆ patte…     ┆            ┆ …          │
│ 2199 ┆ 21     ┆ 96          ┆ e94f194c52 ┆ … ┆ psychology ┆ Q: A non-c ┆ J          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 3dfa5f     ┆   ┆            ┆ ustodial   ┆            ┆ n3-0.6B",  │
│      ┆        ┆             ┆            ┆   ┆            ┆ parent     ┆            ┆ "Qwen/Qwen │
│      ┆        ┆             ┆            ┆   ┆            ┆ asks…      ┆            ┆ …          │
└──────┴────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [69]:
model_name_sort = {
    "Qwen/Qwen3-14B": 1,
    "Qwen/Qwen3-4B": 2,
    "Qwen/Qwen3-0.6B": 3,
}

mad_analysis = apply_parsing_and_group_decision(
    mad_frame, parser, comparer, group_reply
)

table_page_46 = pl.concat(
    [
        (
            mad_analysis.group_by("group_constellation")
            .agg(accuracy=pl.col("is_correct").mean())
            .with_columns(origin=pl.lit("(MAD)"))
        ),
        (
            baseline_analysis.with_columns(
                group_constellation=pl.col("model_name").replace(
                    MODEL_NAME_TO_LETTER_MAPPING
                ),
                origin=pl.lit("(baseline)"),
            ).drop("model_name")
        ),
    ],
    how="diagonal",
)

table_page_46.write_csv(output_dir / "llm_based_table_page_46.csv")

table_page_46

shape: (22, 3)
┌─────────────────────┬──────────┬────────────┐
│ group_constellation ┆ accuracy ┆ origin     │
│ ---                 ┆ ---      ┆ ---        │
│ str                 ┆ f64      ┆ str        │
╞═════════════════════╪══════════╪════════════╡
│ LL                  ┆ 0.32     ┆ (MAD)      │
│ HL                  ┆ 0.57     ┆ (MAD)      │
│ MM                  ┆ 0.61     ┆ (MAD)      │
│ HHM                 ┆ 0.72     ┆ (MAD)      │
│ HLL                 ┆ 0.47     ┆ (MAD)      │
│ …                   ┆ …        ┆ …          │
│ HM                  ┆ 0.65     ┆ (MAD)      │
│ LLM                 ┆ 0.56     ┆ (MAD)      │
│ L                   ┆ 0.37     ┆ (baseline) │
│ M                   ┆ 0.6      ┆ (baseline) │
│ H                   ┆ 0.65     ┆ (baseline) │
└─────────────────────┴──────────┴────────────┘

In [70]:
original_table_page46 = pl.DataFrame(
    {
        "group_constellation": [
            "HHH",
            "HHM",
            "HHL",
            "HML",
            "HMM",
            "H",
            "HLL",
            "MMM",
            "M",
            "MML",
            "MLL",
            "L",
            "LLL",
        ],
        "score (-115 to 115)": [80, 74, 67, 64, 61, 60, 56, 48, 42, 39, 37, 25, 21],
    }
)
original_table_page46.write_csv(output_dir / "human_based_table_page_46.csv")
original_table_page46

shape: (13, 2)
┌─────────────────────┬─────────────────────┐
│ group_constellation ┆ score (-115 to 115) │
│ ---                 ┆ ---                 │
│ str                 ┆ i64                 │
╞═════════════════════╪═════════════════════╡
│ HHH                 ┆ 80                  │
│ HHM                 ┆ 74                  │
│ HHL                 ┆ 67                  │
│ HML                 ┆ 64                  │
│ HMM                 ┆ 61                  │
│ …                   ┆ …                   │
│ M                   ┆ 42                  │
│ MML                 ┆ 39                  │
│ MLL                 ┆ 37                  │
│ L                   ┆ 25                  │
│ LLL                 ┆ 21                  │
└─────────────────────┴─────────────────────┘

In [71]:
decision_schemes = (
    mad_analysis.group_by("group_constellation")
    .map_groups(
        lambda g: calculate_decision_scheme(
            g,
            AnalysisColumn.parsed_individual_answers_before.value,
            AnalysisColumn.parsed_individual_answers_after.value,
            "answer_string",
            group_reply,
            comparer,
        ).select(
            pl.lit(g["group_constellation"].unique().item()).alias(
                "group_constellation"
            ),
            "Correct Members Beginning",
            "correct",
            "incorrect",
        )
    )
    .sort("group_constellation")
)

decision_schemes.write_csv(output_dir / "group_decision_schemes.csv")

decision_schemes

shape: (64, 4)
┌─────────────────────┬───────────────────────────┬──────────┬───────────┐
│ group_constellation ┆ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                 ┆ ---                       ┆ ---      ┆ ---       │
│ str                 ┆ u32                       ┆ f64      ┆ f64       │
╞═════════════════════╪═══════════════════════════╪══════════╪═══════════╡
│ H                   ┆ 1                         ┆ 0.944444 ┆ 0.055556  │
│ H                   ┆ 0                         ┆ 0.142857 ┆ 0.857143  │
│ HH                  ┆ 2                         ┆ 1.0      ┆ 0.0       │
│ HH                  ┆ 1                         ┆ 0.6875   ┆ 0.3125    │
│ HH                  ┆ 0                         ┆ 0.181818 ┆ 0.818182  │
│ …                   ┆ …                         ┆ …        ┆ …         │
│ MM                  ┆ 0                         ┆ 0.083333 ┆ 0.916667  │
│ MMM                 ┆ 3                         ┆ 0.890909 ┆ 0.109091  │
│ MMM                 ┆ 2                         ┆ 1.0      ┆ 0.0       │
│ MMM                 ┆ 1                         ┆ 0.714286 ┆ 0.285714  │
│ MMM                 ┆ 0                         ┆ 0.055556 ┆ 0.944444  │
└─────────────────────┴───────────────────────────┴──────────┴───────────┘

## Unparsable answers:

In [72]:
unparsable_answers_per_model = defaultdict(int)

### In the baseline:

In [73]:
for answer in (
    baseline_frame.with_columns(
        parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
    )
    .filter(pl.col(AnalysisColumn.parsed_answer.value).str.starts_with("___"))
    .select(["final_answer", "model_name"])
    .iter_rows()
):
    print(answer[1], ": \n")
    print(answer[0][-150:])
    print("-" * 50)
    unparsable_answers_per_model[answer[1]] += 1

Qwen/Qwen3-4B :

 annual interest rate as (Total Interest / Principal) * (12 / 12) * 100, but that's the same as before.

Alternatively, maybe the problem is using the
--------------------------------------------------
Qwen/Qwen3-4B :

netic field. The formula for the hyperfine splitting is:

ΔB = (Δf) / (giso)

But if Δf is 500 MHz, then:

ΔB = 500 / 2.12 ≈ 235.8 T. But that's 235,8
--------------------------------------------------
Qwen/Qwen3-4B :

sec². So, if I have h1 - h2 in Btu/lbm, I need to convert it to ft²/sec². Let me use the following conversion:

1 Btu/lbm = 778.169 ft-lbf/lbm

Then,
--------------------------------------------------
Qwen/Qwen3-4B :

ng = T / (r * w * L)

So, solving for w from shear: w² = T / (r * τ_shear)

Solving for L from bearing: L = T / (r * τ_bearing * w)

But since w is
--------------------------------------------------
Qwen/Qwen3-4B :

.

Alternatively, maybe the problem is using the value of Cv for CO2 as 25.1 J/mol·K.

Alternatively, maybe the problem is using the value of Cv for
--------------------------------------------------
Qwen/Qwen3-4B :

citly convert $ M $ to a real. In FORTRAN, `EXP(-M)` would implicitly convert the integer $ M $ to a real, and `M ** X` is valid for integer exponents
--------------------------------------------------
Qwen/Qwen3-4B :

a mistake in the calculation of the angle. Let me check again.

If d = 3.95 Å, λ = 0.248 Å.

Then sinθ = λ / (2d) = 0.248 / (2 * 3.95) = 0.248 / 7.9
--------------------------------------------------
Qwen/Qwen3-0.6B :

he other options don't address the government's right to protect the informant's identity. So the answer should be G.
</think>

The answer is ... (G).
--------------------------------------------------
Qwen/Qwen3-4B :

ke in the calculation of Y.

Wait, maybe the savings identity is S = I + (X - M) + (G - T)? No, that's not correct. The correct identity is S = I + (X
--------------------------------------------------
Qwen/Qwen3-4B :

the resolution is 200 cycles/mm, then:

200 = D / (2.43 * f)

Solving for D:

D = 200 * 2.43 * f

Given that f is 50 mm, then:

D = 200 * 2.43 * 50 =
--------------------------------------------------
Qwen/Qwen3-4B :

iter (option A). But the options here are (A) three times that of Jupiter (so 3:1 ratio), which would be a 1:3 ratio. That's not a resonance. Wait, no
--------------------------------------------------
Qwen/Qwen3-4B :

rsible expansion of an ideal gas, the relation between temperature and pressure is given by $ T_2 = T_1 \left( \frac{P_2}{P_1} \right)^{\frac{\gamma -
--------------------------------------------------
Qwen/Qwen3-4B :

erature. But again, without knowing the critical pressure, this is not helpful.

Alternatively, maybe we can use the fact that the triple point is at
--------------------------------------------------
Qwen/Qwen3-0.6B :

ybe there's a mistake in the options? Or perhaps I misread the problem.

Wait, looking back at the options, (D) is 3.6°C/s. Let me check if there's a
--------------------------------------------------
Qwen/Qwen3-0.6B :

1^{2/3}) $

But since $ T_1 = \frac{P_1 V_1}{n R} $, and $ T_2 = \frac{P_2 V_2}{n R} $, we can express $ V_2^{2/3} $ in terms of $ V_1 $:

From the ad
--------------------------------------------------
Qwen/Qwen3-0.6B :

tion is the product of the marginal distributions. So, if X, Y, Z are jointly Gaussian, then their variances are not necessarily equal. However, since
--------------------------------------------------
Qwen/Qwen3-0.6B :

me 30. So, real GDP is $30. Let me look at the options. Option G is $30. That makes sense. So the answer should be G.
</think>

The answer is ... (G).
--------------------------------------------------
Qwen/Qwen3-0.6B :

k once more. The total amount is $490, which is 450 + 40. So the interest is 40. The rate is 40/(450*12). Let me check if 40 is 17.5% of 450. 17.5% of
--------------------------------------------------
Qwen/Qwen3-0.6B :

on again. The two times are 6:12:43 and 6:52:43. The difference is 40 minutes. So if he left at 6:12:43, he was away for 40 minutes. But since he left
--------------------------------------------------
Qwen/Qwen3-0.6B :

rization. The standard formula is:

ΔH_vap = (mass of the substance) × (ΔT) × (R × 1000) / (1000 × 1000) ?

No, that's not correct. Let me think again
--------------------------------------------------
Qwen/Qwen3-0.6B :

thickness = 1/2 in., width = 3/4 in., length = 2.5 in. So that's a square key with 1/2 in thickness and 1/2 in width, and 2.5 in length. But the shaft
--------------------------------------------------
Qwen/Qwen3-14B :

tate this exactly. However, Option A says "If it's not the case that both Izzy plays Minecraft and Ashleigh stops by then Russell makes dinner." Which
--------------------------------------------------
Qwen/Qwen3-0.6B :

 maybe the velocity coefficient is used with the discharge coefficient. Let me check the formula again.

Alternatively, maybe the velocity coefficient
--------------------------------------------------
Qwen/Qwen3-14B :

hould equal thickness. However, option D has thickness = 0.5 in and width = 0.75 in, which is not a square key. Therefore, this option is invalid. The
--------------------------------------------------
Qwen/Qwen3-14B :

X,Z) = 0.1 * 0.9 = 0.09.

Then, the mutual information between X and Z is (1/2) log(1/(1 - ρ²(X,Z))) = (1/2) log(1/(1 - 0.09²)) = (1/2) log(1/(1 - 0.0
--------------------------------------------------
Qwen/Qwen3-14B :

ely, perhaps the problem is not using the national income identity but another approach. Let me think again. The question is about the current deficit
--------------------------------------------------
Qwen/Qwen3-14B :

. Still not matching the options. The options are around 2.1 to 2.3 degrees. Hmm.

Wait, maybe I made a mistake in the lattice parameter. Let me check
--------------------------------------------------
Qwen/Qwen3-14B :

hout knowing B, this is not helpful. Alternatively, the splitting in terms of magnetic field is ΔB = A / (g_e * μ_B / ħ). But again, without knowing A
--------------------------------------------------
Qwen/Qwen3-14B :

vapor pressure data at that temperature.

This seems like a dead end. Let me go back to the earlier calculation for ΔH_fus. If I assumed ΔP ≈ 1 atm, I
--------------------------------------------------

## In the MAD:

In [74]:
for answer in chain(
    mad_analysis.filter(
        pl.col(AnalysisColumn.parsed_individual_answers_before.value)
        .list.eval(pl.element().str.starts_with("___"))
        .list.any()
    )
    .select(
        "answers_at_beginning",
        AnalysisColumn.parsed_individual_answers_before.value,
        "model_names",
    )
    .iter_rows(),
    mad_analysis.filter(
        pl.col(AnalysisColumn.parsed_individual_answers_before.value)
        .list.eval(pl.element().str.starts_with("___"))
        .list.any()
    )
    .select(
        "answers_at_end",
        AnalysisColumn.parsed_individual_answers_after.value,
        "model_names",
    )
    .iter_rows(),
):
    for i, parsed in enumerate(answer[1]):
        if parsed.startswith("___"):
            unparsable_answers_per_model[answer[2][i]] += 1
            print(parsed, f"from {answer[2][i]}: \n")
            print(answer[0][i][-150:])
            print("-" * 50)

___not_parsable___ from Qwen/Qwen3-14B:

 Converting to ft²/sec², since 1 ft·lbf = 32.174 ft²/sec², so R = 85.78 * 32.174 ≈ 2760 ft²/sec²·°R.

Temperature T1 is 600°F, which is 600 + 459.67 =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 planes. Then d = a / sqrt(2) ≈ 6.29 / 1.414 ≈ 4.45 Å. Then:

sinθ = 0.248 / (2 * 4.45) ≈ 0.248 / 8.9 ≈ 0.0279

θ ≈ 1.6 degrees. Still not matching.


--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ħ^2) / (μ_0 * 4π * r^3) * something. But without knowing r, this is not helpful.

Alternatively, the hyperfine splitting in terms of magnetic field is
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

, according to the derivation, they are the same. Therefore, the key is designed based on shear stress.

So the options that satisfy τ ≤ 11,000 are B
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

t budget deficit plus the difference in tax revenues and government spending due to the change in GNP.

But how?

Alternatively, the full employment
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

/ π

So:

500e6 = (2.12 * 2.8025e8 * B) / π

Solving for B:

B = (500e6 * π) / (2.12 * 2.8025e8) ≈ (1.57e9) / (5.93e8) ≈ 2.65 T

Still too large. This
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 2.12, μ = 9.273e-24 J/T, c = 3e8 m/s.

Numerator: 2.12 * 9.273e-24 * 3e8 = 2.12 * 9.273 * 3e-16. Let's compute 2.12 * 9.273 = 19.65876. Multiply by
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

5 * 1.67e-27 * 4e14 = 0.5 * 6.68e-13 = 3.34e-13 J. Correct.

So that's correct.

Then, one-third of that is 1.113e-13 J.

But then, the power is 1.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

quid. The molar volume of the solid is 70.588 cm³/mol, and the liquid is 75 cm³/mol.

The enthalpy of fusion can be calculated using the formula ∆H_f
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

ance of 10 meters: 441 * 10 = 4410 joules.

Looking at the options, option (I) is 4410 joules. So the answer should be (I).
</think>

A: 4410 joules.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

options again. Wait, maybe the total amount paid is $1840, and the down payment is $50, so the interest is $1790. Then, the interest rate is (1790 / 1
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

units are consistent, and the calculation seems right. So the correct option is (I).
</think>

(A): $9.30 \times 10^{-15} \mathrm{C} \cdot \mathrm{m}$
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

0 V.

So hc = 6.626e-34 * 3e8 = 1.9878e-25 J·m. eV = 1.602e-19 * 5e4 = 8.01e-15 C·V. Then λ_min = 1.9878e-25 / 8.01e-15 ≈ 2.48e-11 m = 0.0248 nm = 0.2
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

hy, and a grade 3/6 murmur, all of which are characteristic of aortic dissection. The other options do not align with the clinical features described.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

erefore, the answer should be (A).
</think>

(A): If it's not the case that both Izzy plays Minecraft and Ashleigh stops by then Russell makes dinner.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

qrt(5,007,200) ≈ 2238 ft/s. Then, applying the coefficients: 2238 * 0.92 * 0.95 ≈ 1955 ft/s. But this is not in the options. However, option E is 3697
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

ly, the diffraction limit is given by the formula:

R = 1.22 * λ / (D * f)

But I need to solve for D.

Given R = 200 lines/mm, λ = 550 nm, f = 50 mm
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

l was $6 million, so the total is $106 million. The price increased by 20%, so the new price is $106 * 1.2 = $127.2 million. But the builder said they
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

yperosmolality and potassium/lactate levels are more about fluid balance. So, the correct answer should be C.
</think>

(A): An excess of lactic acid.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 h), where h is the head in meters. Let's try with h = 0.1 m.

V = 0.95 * 0.92 * sqrt(2 * 9.81 * 0.1) ≈ 0.95 * 0.92 * sqrt(1.962) ≈ 0.95 * 0.92 * 1.4
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

rom different centuries, like the early 4th century BCE, which might be too early. The answer should be (C).
</think>

A: (C) Early Fifth Century BCE.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

30). But that's a rough estimate. Alternatively, if the angle is measured from the normal, then θ is 70°, and using d=0.326 nm:

λ = 2 * 0.326 * sin(7
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

t I'm not 100% sure. However, based on my knowledge, 250 billion is a plausible number for chicken meat production in 2018.
</think>

(A): 250 billion
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

/ (J/T·Hz) = (J·s·T) / (J/T·Hz) = (s·T²)/Hz.

But this doesn't seem to give the right units for A. I think I'm making a mistake in the formula. Let me
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:


No, that's not helpful.

Alternatively, maybe the vapor pressure is given by the formula:

P = (molar mass) * (ΔT) * (R * ln(T_c / T_m)) / (R * ln(T
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

decay. Yes, that makes sense. So the answer should be E.
</think>

The tendency for migration to decrease with distance is called (E): distance decay.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

076e23)

Calculate numerator: 4 * 0.0746 = 0.2984 kg/mol

Denominator: 1.99e3 * 6.02214076e23 = 1.99 * 6.02214076e26 ≈ 11.984e26 kg/(m³·mol)

So a³ =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ation. Let me check the calculation again.

Wait, the formula for density is ρ = (Z * M) / (N_A * a³). Let me plug in the numbers again:

Z = 4
M = 74
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

, maybe the current deficit is $18.07 billion, which would be option A. But I can't see why. Alternatively, maybe I made a mistake in the calculation.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

ion B says decreases, decreases, increases. That matches what I thought. So the answer should be B.
</think>

(A): Decreases    Decreases    Increases
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

gle between the hour and minute hands is |30H - 5.5M|. So when H is the hour, M is the minutes. So for example, at 6:00, it's 180 degrees. At 6:50, it
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

nd up. Therefore, the new waist size is 36 inches.

Looking at the options, option A is 36 inches. So the answer should be A.
</think>

A: 36 inches.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

hat both shear and bearing stresses are exactly at the allowable limits.

Let me set up the equations again:

From shear stress: τ = (T / r) / (t²) =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

allowable 22,000 psi. So that's okay. So option (C) would be acceptable. But earlier when I calculated using the shear stress formula τ = F / A, I got
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ocity in terms of the pressure and the specific volume. For an isentropic process, the enthalpy change can be related to the pressure change. However,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

.7-0.8 in², and exit area around 8-9 in². If the mass flow rate is 12,000 lb/hr, and the velocity at the throat is around 3697 ft/sec (from option E),
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

X and Z is equal to the covariance between X and Z multiplied by the logarithm of the ratio of the variances. Wait, no, that's not correct. The mutual
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

and it's 2 M, then the moles should be 2 times 3, which is 6. Let me check the options. Option C is 6. So the answer should be C.
</think>

(A): 6 mol
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 math: 6000 divided by 200 is 30. So, real GDP should be $30. Looking at the options, option G is $30. So the answer should be G.
</think>

A: (G) $30
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

are similar but not matching. So the correct answer should be B.
</think>

(A): FUNCTION P(X,M) INTEGER X, M P = EXP(-M) * M ** X / FACT(X) RETURN END
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 of products would be N2 : H2 : 2NH. But since the rate constants are given, we need to find the ratio based on the given k_a/k_b/k_c.

Alternatively
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

alories. So 730,000 / 0.49 = 1,489,796 grams. But that's 1,489.8 kg. However, the per day calculation gives 14.9 kg. So there's a factor of 100 error.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

, perhaps I should use the formula for the interplanar spacing in terms of the density.

The formula for the interplanar spacing d is given by d = (n
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

τ = F / (L * t). Let's try that.

For option (C): L = 2 in, t = 1 in. So shear area = 2 * 1 = 2 in². τ = 20,000 / 2 = 10,000 psi, which is below 11,00
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

λ = 550e-6 mm, f = 50 mm:

D = 200 * 550e-6 * 50

Calculate:

550e-6 * 50 = 0.0275

Multiply by 200: 0.0275 * 200 = 5.5 mm

So D = 5.5 mm. The options
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

290 / 5.5 = 52.727 minutes

So the times are approximately 12.727 and 52.727 minutes after 6 p.m. Since he returned before 7 p.m., which is 60 minutes
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

/mol. If the specific heat is 0.2 Btu/(lb·°R), then Q = 0.2 * 0.09699 * 3000 ≈ 58.2 Btu. Still not matching.

This is really puzzling. The options are
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

think>

A: (H) A central planning committee allocates resources in the Soviet economy, while supply and demand dictate allocation in a market economy.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

rnatively, maybe the problem is using the specific heat in terms of Btu per pound-mole? For example, if the specific heat is 28.46 J/(mol·K), which is
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

nd up. Therefore, the new waist size is 36 inches.

Looking at the options, option A is 36 inches. So the answer should be A.
</think>

A: 36 inches.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 math: 6000 divided by 200 is 30. So, real GDP should be $30. Looking at the options, option G is $30. So the answer should be G.
</think>

A: (G) $30
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 = 40.123 mT = 1.09876 cm⁻¹

(C): 500 MHz = 16.850 mT = 0.01667 cm⁻¹

(D): 500 MHz = 45.672 mT = 2.86329 cm⁻¹

(E): 500 MHz = 70.456 mT = 4.32109 cm⁻¹
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

7.2 million = $107.2 million. But the builder said they agreed to increase to $101 million. That's a $6.2 million increase. That seems like a big jump
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

and it's 2 M, then the moles should be 2 times 3, which is 6. Let me check the options. Option C is 6. So the answer should be C.
</think>

(A): 6 mol
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

. For (110), d = a / sqrt(1² + 1² + 0²) = a / sqrt(2) ≈ 6.29 / 1.414 ≈ 4.45 Å. Then sinθ = 0.248 / (2 * 4.45) ≈ 0.248 / 8.9 ≈ 0.0279, θ ≈ 1.6 degrees.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

N_A.

But since the crystal is cubic, the number of ions per unit volume is also equal to the number of K+ ions per unit volume plus the number of Cl
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

raft and Ashleigh stops by then Russell makes dinner." This is confusing. If it's "both not the case that Izzy plays Minecraft and Ashleigh stops by,"
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

Therefore, the answer should be A.
</think>

(A): If it's not the case that both Izzy plays Minecraft and Ashleigh stops by then Russell makes dinner.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ound interest. Let's compute (1.0155)^12:

We can use the formula (1 + r)^n = e^{n * ln(1 + r)}.

ln(1.0155) ≈ 0.01537 (as before). Multiply by 12: 0.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

* ∆V)] * (-0.02 K)

So:

P_triple = 1 atm - [∆H_fus / (T * ∆V)] * 0.02 K

Let's recalculate with this corrected sign.

Using option B: ∆H_fus=1.5 kcal
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

limation (∆H_S) = ∆H_vap + ∆H_fus ≈ 11.35 kcal/mol.

3. **Vapor Pressure at the Triple Point (P_1):**
   Using the Clausius-Clapeyron equation for
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

yperosmolality and potassium/lactate levels are more about fluid balance. So, the correct answer should be C.
</think>

(A): An excess of lactic acid.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

uct step by step:

First, multiply 3/2 * 7/6 = (3*7)/(2*6) = 21/12 = 7/4.

Then multiply by 13/12: 7/4 * 13/12 = 91/48.

Multiply by 21/20: 91/48 * 21
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

36.

So T2 ≈ 300 * 7.36 ≈ 2208 K.

But none of the options are that.

Wait, maybe the options are in different units? Or maybe the initial pressure
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

8.0 × 10^-14 cal.

Then, power is current (4.8 × 10^-6 A) multiplied by energy per proton (8.0 × 10^-14 cal/A) = 4.8 × 10^-6 * 8.0 × 10^-14 = 3.84 ×
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 ln(P2/P1) ≈ -1.866e-4

Therefore, P2/P1 ≈ exp(-1.866e-4) ≈ 1 - 1.866e-4 ≈ 0.999813

So P2 ≈ 760 mmHg * 0.999813 ≈ 759.86 mmHg

But this suggests that
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

). If the correlation between X and Z is ρ1*ρ2, then that formula applies. But in the example where ρ1=0.5 and ρ2=0.5, the mutual information would be
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

on. But this isn't an option. The options given are (A) $18.07, (B) $12.5, etc. So this suggests that my approach is incorrect.

Wait, maybe I need to
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 However, the options given are (A) $18.07, (B) $12.5, etc. So, this suggests that my assumption about the savings rate is incorrect.

Alternatively,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

ia refers to an increase in the entire population of cells, while in plants and animals, it refers to the increase in size of the individual organism.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

it, but the options are in eV. Wait, maybe the question is wrong. Alternatively, maybe I made a mistake in the formula. Let me think again. The recoil
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

g to real is not necessary. However, the formula requires m^x, which is a real number. Therefore, the code should convert M to a real. But in option B
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 that. Wait, maybe the options are written with different variables. For example, maybe option A is correct. Let me check again.

Option A: EXP(M) * M
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

ich is the ratio between the actual velocity and the velocity in the nozzle.

So, if the theoretical velocity is v, then the actual velocity is v * 0
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

decay. Yes, that makes sense. So the answer should be E.
</think>

The tendency for migration to decrease with distance is called (E): distance decay.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

e incident beam and the crystal planes is 20°, then θ = 20°, and using that would give a different result. Let's try that. If θ = 20°, then using d =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

ate for each option:

Option A: thickness = 1/2 in., width = 1/2 in., length = 3 in.

x = 1/2 in. (since width and thickness are same)

L = 3 in.

So,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

ifferent value for the specific enthalpy difference. For example, if the specific enthalpy difference is 1000 Btu/lbm, then the ideal velocity is sqrt
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ill a bit less than 380. So need a slightly lower rate than 1.55% monthly. Let's try 1.54% monthly.

ln(1.0154) ≈ 0.01526. Multiply by 12: 0.1831. e^0
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

 suggests that my approach is wrong.

Wait, maybe the formula is different. The hyperfine splitting in EPR is given by the formula:

Δ = (giso * γ * B
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

y. Alternatively, the splitting is given by:

Δf = (giso * μ_N * B) / (h * 2π)

But the splitting is 500 MHz, which is the splitting between the lines
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:


-> Qwen 0.6B often says "Answer should be A /think. The Answer is G"

In [75]:
unparsable_answers_per_model

defaultdict(int,
            {'Qwen/Qwen3-4B': 161,
             'Qwen/Qwen3-0.6B': 371,
             'Qwen/Qwen3-14B': 145})

### Build an overview of parsing error Influence

In [76]:
baseline_frame_with_group_constellation = baseline_frame.with_columns(
    group_constellation=pl.col("model_name").replace(MODEL_NAME_TO_LETTER_MAPPING)
    + pl.lit(" (Baseline)")
).drop("model_name")

parsing_error_influence_table = pl.DataFrame(
    {
        "group_constellation": mad_analysis["group_constellation"]
        .unique()
        .extend(baseline_frame_with_group_constellation["group_constellation"].unique())
        .sort()
    }
)

for handling in ["null", "wrong", "random"]:
    new_comparer = AnswerComparer(AnswerOptions.letters_A_to_J, handling)

    new_mad = (
        apply_parsing_and_group_decision(mad_frame, parser, new_comparer, group_reply)
        .group_by("group_constellation")
        .agg(accuracy=pl.col("is_correct").mean())
    )

    new_base = (
        baseline_frame_with_group_constellation.with_columns(
            parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
        )
        .with_columns(
            is_correct=new_comparer(
                pl.col(AnalysisColumn.parsed_answer.value), pl.col("answer_string")
            )
        )
        .group_by("group_constellation")
        .agg(accuracy=pl.col("is_correct").mean())
    )

    parsing_error_influence_table = parsing_error_influence_table.join(
        pl.concat([new_mad, new_base], how="diagonal").select(
            "group_constellation",
            pl.col("accuracy").alias(f"Accuracy ({handling})"),
        ),
        on="group_constellation",
        how="inner",
    )

parsing_error_influence_table.with_columns(
    deviation=(
        pl.max_horizontal(pl.exclude("group_constellation"))
        - pl.min_horizontal(pl.exclude("group_constellation"))
    ).alias("range")
)

shape: (22, 5)
┌─────────────────────┬─────────────────┬──────────────────┬───────────────────┬───────────┐
│ group_constellation ┆ Accuracy (null) ┆ Accuracy (wrong) ┆ Accuracy (random) ┆ deviation │
│ ---                 ┆ ---             ┆ ---              ┆ ---               ┆ ---       │
│ str                 ┆ f64             ┆ f64              ┆ f64               ┆ f64       │
╞═════════════════════╪═════════════════╪══════════════════╪═══════════════════╪═══════════╡
│ HM                  ┆ 0.684783        ┆ 0.63             ┆ 0.64              ┆ 0.054783  │
│ LM                  ┆ 0.609195        ┆ 0.53             ┆ 0.56              ┆ 0.079195  │
│ HHL                 ┆ 0.663265        ┆ 0.65             ┆ 0.65              ┆ 0.013265  │
│ LMM                 ┆ 0.646465        ┆ 0.64             ┆ 0.64              ┆ 0.006465  │
│ HLL                 ┆ 0.474747        ┆ 0.47             ┆ 0.47              ┆ 0.004747  │
│ …                   ┆ …               ┆ …                ┆ …                 ┆ …         │
│ H                   ┆ 0.734694        ┆ 0.72             ┆ 0.72              ┆ 0.014694  │
│ HHH                 ┆ 0.760417        ┆ 0.73             ┆ 0.73              ┆ 0.030417  │
│ M (Baseline)        ┆ 0.670455        ┆ 0.59             ┆ 0.6               ┆ 0.080455  │
│ L (Baseline)        ┆ 0.388889        ┆ 0.35             ┆ 0.37              ┆ 0.038889  │
│ H (Baseline)        ┆ 0.688172        ┆ 0.64             ┆ 0.66              ┆ 0.048172  │
└─────────────────────┴─────────────────┴──────────────────┴───────────────────┴───────────┘

-> Using (null) is the best, as unparsed values increase your score... should not be used

-> Using wrong is the worst, could possibly be used to be fair, as it is "not correct"

-> Papers and Benchmarks often use "random", which increases the values artificially and introduces noise.. I do not like it, but to be fair one should use it.

---

-> But in all of out cases, even absolute deviation is actually pretty low. (it gets mitigated in group decisions, as unparsable values are ignored in aggregation)

# Agreeableness -> Number of Cases where they reach conslusion

In [77]:
unanimity = (
    mad_analysis.with_columns(
        pl.col(AnalysisColumn.parsed_individual_answers_after.value)
        .list.n_unique()
        .eq(1)
        .alias("End unanimity"),
        pl.col(AnalysisColumn.parsed_individual_answers_before.value)
        .list.n_unique()
        .eq(1)
        .alias("Start unanimity"),
    )
    .group_by("group_constellation")
    .agg(
        pl.col("End unanimity").mean(),
        pl.col("Start unanimity").mean(),
        pl.when(pl.col("Start unanimity"))
        .then(None)
        .otherwise(pl.col("End unanimity"))
        .mean()
        .alias("End Unanimity | not Start Unanimity"),
        pl.when(pl.col("Start unanimity"))
        .then(pl.col("End unanimity"))
        .otherwise(None)
        .mean()
        .alias("End Unanimity | Start Unanimity"),
        accuracy=pl.col("is_correct").mean(),
    )
)

unanimity

shape: (19, 6)
┌─────────────────┬───────────────┬─────────────────┬─────────────────┬─────────────────┬──────────┐
│ group_constella ┆ End unanimity ┆ Start unanimity ┆ End Unanimity | ┆ End Unanimity | ┆ accuracy │
│ tion            ┆ ---           ┆ ---             ┆ not Start Unan… ┆ Start Unanimit… ┆ ---      │
│ ---             ┆ f64           ┆ f64             ┆ ---             ┆ ---             ┆ f64      │
│ str             ┆               ┆                 ┆ f64             ┆ f64             ┆          │
╞═════════════════╪═══════════════╪═════════════════╪═════════════════╪═════════════════╪══════════╡
│ H               ┆ 1.0           ┆ 1.0             ┆ null            ┆ 1.0             ┆ 0.72     │
│ LLM             ┆ 0.74          ┆ 0.23            ┆ 0.701299        ┆ 0.869565        ┆ 0.56     │
│ LM              ┆ 0.8           ┆ 0.32            ┆ 0.794118        ┆ 0.8125          ┆ 0.54     │
│ HHL             ┆ 0.76          ┆ 0.3             ┆ 0.685714        ┆ 0.933333        ┆ 0.65     │
│ L               ┆ 1.0           ┆ 1.0             ┆ null            ┆ 1.0             ┆ 0.26     │
│ …               ┆ …             ┆ …               ┆ …               ┆ …               ┆ …        │
│ HHH             ┆ 0.95          ┆ 0.75            ┆ 0.84            ┆ 0.986667        ┆ 0.73     │
│ MM              ┆ 0.93          ┆ 0.88            ┆ 0.916667        ┆ 0.931818        ┆ 0.61     │
│ HM              ┆ 0.91          ┆ 0.75            ┆ 0.88            ┆ 0.92            ┆ 0.65     │
│ HMM             ┆ 0.89          ┆ 0.7             ┆ 0.933333        ┆ 0.871429        ┆ 0.58     │
│ M               ┆ 1.0           ┆ 1.0             ┆ null            ┆ 1.0             ┆ 0.51     │
└─────────────────┴───────────────┴─────────────────┴─────────────────┴─────────────────┴──────────┘

-> In Human Groups (see Group Problem Solving) there is the tendency that the smarter the group, the more it is a "Truth Supported" Decision Scheme, the "dumber" the group, the more it is "proportional"

### Correlation for groups (ignoring 1 member, as it is always 1)

In [78]:
print("Pearson Correlation:")
print(
    unanimity.filter(pl.col("group_constellation").str.len_chars() > 1)
    .select(pl.exclude("group_constellation"))
    .corr()
)

print("Spearman Rank Correlation:")

print(
    unanimity.filter(pl.col("group_constellation").str.len_chars() > 1)
    .select(pl.exclude("group_constellation"))
    .with_columns(pl.all().rank())
    .corr()
)

Pearson Correlation:
shape: (5, 5)
┌───────────────┬─────────────────┬─────────────────────┬───────────────────────┬──────────┐
│ End unanimity ┆ Start unanimity ┆ End Unanimity | not ┆ End Unanimity | Start ┆ accuracy │
│ ---           ┆ ---             ┆ Start Unan…         ┆ Unanimit…             ┆ ---      │
│ f64           ┆ f64             ┆ ---                 ┆ ---                   ┆ f64      │
│               ┆                 ┆ f64                 ┆ f64                   ┆          │
╞═══════════════╪═════════════════╪═════════════════════╪═══════════════════════╪══════════╡
│ 1.0           ┆ 0.798546        ┆ 0.886054            ┆ 0.429095              ┆ 0.39612  │
│ 0.798546      ┆ 1.0             ┆ 0.63738             ┆ 0.468368              ┆ 0.335234 │
│ 0.886054      ┆ 0.63738         ┆ 1.0                 ┆ 0.031864              ┆ 0.327081 │
│ 0.429095      ┆ 0.468368        ┆ 0.031864            ┆ 1.0                   ┆ 0.329198 │
│ 0.39612       ┆ 0.335234        ┆ 0.327081            ┆ 0.329198              ┆ 1.0      │
└───────────────┴─────────────────┴─────────────────────┴───────────────────────┴──────────┘
Spearman Rank Correlation:
shape: (5, 5)
┌───────────────┬─────────────────┬─────────────────────┬───────────────────────┬──────────┐
│ End unanimity ┆ Start unanimity ┆ End Unanimity | not ┆ End Unanimity | Start ┆ accuracy │
│ ---           ┆ ---             ┆ Start Unan…         ┆ Unanimit…             ┆ ---      │
│ f64           ┆ f64             ┆ ---                 ┆ ---                   ┆ f64      │
│               ┆                 ┆ f64                 ┆ f64                   ┆          │
╞═══════════════╪═════════════════╪═════════════════════╪═══════════════════════╪══════════╡
│ 1.0           ┆ 0.886432        ┆ 0.665195            ┆ 0.578792              ┆ 0.57732  │
│ 0.886432      ┆ 1.0             ┆ 0.642596            ┆ 0.51475               ┆ 0.365782 │
│ 0.665195      ┆ 0.642596        ┆ 1.0                 ┆ -0.060339             ┆ 0.367918 │
│ 0.578792      ┆ 0.51475         ┆ -0.060339           ┆ 1.0                   ┆ 0.469809 │
│ 0.57732       ┆ 0.365782        ┆ 0.367918            ┆ 0.469809              ┆ 1.0      │
└───────────────┴─────────────────┴─────────────────────┴───────────────────────┴──────────┘

-> significantly correlated

---
-> Accuracy Correlates with Unanimity
Of course this could be that if everyone is correct in the beginning, then if they that way, then the chance of being correct is higher,
But can we increase the accuracy by accepting when a group starts with one answer?

## Analysis: Is the group finding answers "together" ? (e.g. can it find answers out of wrong start)

In [79]:
correctness_influence = (
    mad_analysis.with_columns(
        correct_before=comparer(
            pl.col(AnalysisColumn.parsed_combined_answers_before.value),
            pl.col("answer_string"),
        )
    )
    .group_by("group_constellation")
    .agg(
        pl.when(pl.col("correct_before"))
        .then(pl.col("is_correct"))
        .otherwise(None)
        .mean()
        .alias("Correct | Correct in Beginning"),
        pl.when(pl.col("correct_before"))
        .then(None)
        .otherwise(pl.col("is_correct"))
        .mean()
        .alias("Correct | !Correct in Beginning"),
        accuracy=pl.col("is_correct").mean(),
    )
)

correctness_influence

shape: (19, 4)
┌─────────────────────┬────────────────────────────────┬───────────────────────┬──────────┐
│ group_constellation ┆ Correct | Correct in Beginning ┆ Correct | !Correct in ┆ accuracy │
│ ---                 ┆ ---                            ┆ Beginnin…             ┆ ---      │
│ str                 ┆ f64                            ┆ ---                   ┆ f64      │
│                     ┆                                ┆ f64                   ┆          │
╞═════════════════════╪════════════════════════════════╪═══════════════════════╪══════════╡
│ LLM                 ┆ 0.833333                       ┆ 0.307692              ┆ 0.56     │
│ HL                  ┆ 0.904762                       ┆ 0.327586              ┆ 0.57     │
│ HHH                 ┆ 0.958333                       ┆ 0.142857              ┆ 0.73     │
│ H                   ┆ 0.944444                       ┆ 0.142857              ┆ 0.72     │
│ HLM                 ┆ 0.936508                       ┆ 0.216216              ┆ 0.67     │
│ …                   ┆ …                              ┆ …                     ┆ …        │
│ HLL                 ┆ 0.880952                       ┆ 0.172414              ┆ 0.47     │
│ LLL                 ┆ 0.805556                       ┆ 0.1875                ┆ 0.41     │
│ HMM                 ┆ 0.873016                       ┆ 0.081081              ┆ 0.58     │
│ HHL                 ┆ 0.909091                       ┆ 0.147059              ┆ 0.65     │
│ HM                  ┆ 0.938462                       ┆ 0.114286              ┆ 0.65     │
└─────────────────────┴────────────────────────────────┴───────────────────────┴──────────┘

While the difference in Correct | Correct in Beginning is negligible, the true power lies in changing the answer when They are not correct.

In [80]:
(
    correctness_influence.join(unanimity, how="left", on="group_constellation")
    .filter(pl.col("group_constellation").str.len_chars() > 1)
    .select(pl.exclude("group_constellation"))
    .with_columns(pl.all().rank())
    .corr()
)

shape: (8, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ Correct |  ┆ Correct |  ┆ accuracy  ┆ End        ┆ Start     ┆ End       ┆ End       ┆ accuracy_ │
│ Correct in ┆ !Correct   ┆ ---       ┆ unanimity  ┆ unanimity ┆ Unanimity ┆ Unanimity ┆ right     │
│ Beginning  ┆ in         ┆ f64       ┆ ---        ┆ ---       ┆ | not     ┆ | Start   ┆ ---       │
│ ---        ┆ Beginnin…  ┆           ┆ f64        ┆ f64       ┆ Start     ┆ Unanimit… ┆ f64       │
│ f64        ┆ ---        ┆           ┆            ┆           ┆ Unan…     ┆ ---       ┆           │
│            ┆ f64        ┆           ┆            ┆           ┆ ---       ┆ f64       ┆           │
│            ┆            ┆           ┆            ┆           ┆ f64       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0        ┆ -0.16777   ┆ 0.875644  ┆ 0.556292   ┆ 0.417098  ┆ 0.382353  ┆ 0.384106  ┆ 0.875644  │
│ -0.16777   ┆ 1.0        ┆ -0.035346 ┆ -0.307806  ┆ -0.379794 ┆ -0.309051 ┆ -0.019882 ┆ -0.035346 │
│ 0.875644   ┆ -0.035346  ┆ 1.0       ┆ 0.57732    ┆ 0.365782  ┆ 0.367918  ┆ 0.469809  ┆ 1.0       │
│ 0.556292   ┆ -0.307806  ┆ 0.57732   ┆ 1.0        ┆ 0.886432  ┆ 0.665195  ┆ 0.578792  ┆ 0.57732   │
│ 0.417098   ┆ -0.379794  ┆ 0.365782  ┆ 0.886432   ┆ 1.0       ┆ 0.642596  ┆ 0.51475   ┆ 0.365782  │
│ 0.382353   ┆ -0.309051  ┆ 0.367918  ┆ 0.665195   ┆ 0.642596  ┆ 1.0       ┆ -0.060339 ┆ 0.367918  │
│ 0.384106   ┆ -0.019882  ┆ 0.469809  ┆ 0.578792   ┆ 0.51475   ┆ -0.060339 ┆ 1.0       ┆ 0.469809  │
│ 0.875644   ┆ -0.035346  ┆ 1.0       ┆ 0.57732    ┆ 0.365782  ┆ 0.367918  ┆ 0.469809  ┆ 1.0       │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

## Influence of Group Aggregation Protocol

In [81]:
group_reply_influence_table = pl.DataFrame(
    {
        "group_constellation": mad_analysis["group_constellation"]
        .unique()
        .extend(baseline_frame_with_group_constellation["group_constellation"].unique())
        .sort()
    }
)

for strategy in [MajorityVote(), SingularityVote()]:
    new_group_reply_agg = GroupReplyAggregator(strategy)
    group_reply_influence_table = group_reply_influence_table.join(
        apply_parsing_and_group_decision(
            mad_frame, parser, comparer, new_group_reply_agg
        )
        .group_by("group_constellation")
        .agg(accuracy=pl.col("is_correct").mean())
        .select(
            "group_constellation",
            pl.col("accuracy").alias(f"Accuracy ({strategy.__class__.__name__})"),
        ),
        on="group_constellation",
        how="inner",
    )

group_reply_influence_table = group_reply_influence_table.with_columns(
    deviation=(
        pl.max_horizontal(pl.exclude("group_constellation"))
        - pl.min_horizontal(pl.exclude("group_constellation"))
    ).alias("range")
)

group_reply_influence_table

shape: (19, 4)
┌─────────────────────┬─────────────────────────┬────────────────────────────┬───────────┐
│ group_constellation ┆ Accuracy (MajorityVote) ┆ Accuracy (SingularityVote) ┆ deviation │
│ ---                 ┆ ---                     ┆ ---                        ┆ ---       │
│ str                 ┆ f64                     ┆ f64                        ┆ f64       │
╞═════════════════════╪═════════════════════════╪════════════════════════════╪═══════════╡
│ LLL                 ┆ 0.41                    ┆ 0.4                        ┆ 0.01      │
│ HMM                 ┆ 0.58                    ┆ 0.55                       ┆ 0.03      │
│ HHL                 ┆ 0.65                    ┆ 0.57                       ┆ 0.08      │
│ L                   ┆ 0.25                    ┆ 0.25                       ┆ 0.0       │
│ LLM                 ┆ 0.56                    ┆ 0.52                       ┆ 0.04      │
│ …                   ┆ …                       ┆ …                          ┆ …         │
│ HL                  ┆ 0.58                    ┆ 0.59                       ┆ 0.01      │
│ HM                  ┆ 0.63                    ┆ 0.63                       ┆ 0.0       │
│ LMM                 ┆ 0.65                    ┆ 0.6                        ┆ 0.05      │
│ H                   ┆ 0.72                    ┆ 0.72                       ┆ 0.0       │
│ LM                  ┆ 0.56                    ┆ 0.52                       ┆ 0.04      │
└─────────────────────┴─────────────────────────┴────────────────────────────┴───────────┘

In [82]:
group_reply_influence_table.drop("group_constellation").with_columns(
    pl.all().rank()
).corr()

shape: (3, 3)
┌─────────────────────────┬────────────────────────────┬───────────┐
│ Accuracy (MajorityVote) ┆ Accuracy (SingularityVote) ┆ deviation │
│ ---                     ┆ ---                        ┆ ---       │
│ f64                     ┆ f64                        ┆ f64       │
╞═════════════════════════╪════════════════════════════╪═══════════╡
│ 1.0                     ┆ 0.962522                   ┆ 0.248674  │
│ 0.962522                ┆ 1.0                        ┆ 0.055508  │
│ 0.248674                ┆ 0.055508                   ┆ 1.0       │
└─────────────────────────┴────────────────────────────┴───────────┘

-> Slightly Negative Correlation between Accuracy and the deviation, meaning the better the more MajorityVote == SingularityVote -> Same argument as before

## Inter-Model Correctness Correlation (Aka answer diversity)

In [83]:
mad_analysis

shape: (1_900, 23)
┌──────┬────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id   ┆ run_id ┆ question_id ┆ phoenix_sp ┆ … ┆ group_cons ┆ ___parsed_ ┆ ___parsed_ ┆ is_correct │
│ ---  ┆ ---    ┆ ---         ┆ an_id      ┆   ┆ tellation  ┆ combined_a ┆ combined_a ┆ ---        │
│ i64  ┆ i64    ┆ i64         ┆ ---        ┆   ┆ ---        ┆ nswers_bef ┆ nswers_aft ┆ bool       │
│      ┆        ┆             ┆ str        ┆   ┆ str        ┆ …          ┆ …          ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ ---        ┆ ---        ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ str        ┆ str        ┆            │
╞══════╪════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 230  ┆ 3      ┆ 63          ┆ bf94cefe4f ┆ … ┆ H          ┆ C          ┆ C          ┆ true       │
│      ┆        ┆             ┆ 7d6a67     ┆   ┆            ┆            ┆            ┆            │
│ 231  ┆ 3      ┆ 6           ┆ 997b3806bf ┆ … ┆ H          ┆ D          ┆ D          ┆ false      │
│      ┆        ┆             ┆ b3898e     ┆   ┆            ┆            ┆            ┆            │
│ 238  ┆ 3      ┆ 41          ┆ 17efe8d5fd ┆ … ┆ H          ┆ I          ┆ I          ┆ true       │
│      ┆        ┆             ┆ 7b7069     ┆   ┆            ┆            ┆            ┆            │
│ 239  ┆ 3      ┆ 105         ┆ 1ab4b05cf3 ┆ … ┆ H          ┆ I          ┆ I          ┆ true       │
│      ┆        ┆             ┆ 0bf020     ┆   ┆            ┆            ┆            ┆            │
│ 248  ┆ 3      ┆ 8           ┆ c385b50db1 ┆ … ┆ H          ┆ D          ┆ D          ┆ false      │
│      ┆        ┆             ┆ 39472a     ┆   ┆            ┆            ┆            ┆            │
│ …    ┆ …      ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2195 ┆ 21     ┆ 10          ┆ c21a7361cd ┆ … ┆ LMM        ┆ ___differe ┆ A          ┆ false      │
│      ┆        ┆             ┆ d9e460     ┆   ┆            ┆ nt_votes__ ┆            ┆            │
│      ┆        ┆             ┆            ┆   ┆            ┆ _          ┆            ┆            │
│ 2196 ┆ 21     ┆ 14          ┆ 95c6302a0f ┆ … ┆ LMM        ┆ H          ┆ H          ┆ true       │
│      ┆        ┆             ┆ 46a9fb     ┆   ┆            ┆            ┆            ┆            │
│ 2197 ┆ 21     ┆ 45          ┆ 6228e2254e ┆ … ┆ LMM        ┆ E          ┆ E          ┆ false      │
│      ┆        ┆             ┆ f5fcda     ┆   ┆            ┆            ┆            ┆            │
│ 2198 ┆ 21     ┆ 43          ┆ 2d8bf17996 ┆ … ┆ LMM        ┆ H          ┆ H          ┆ true       │
│      ┆        ┆             ┆ c57d3a     ┆   ┆            ┆            ┆            ┆            │
│ 2199 ┆ 21     ┆ 96          ┆ e94f194c52 ┆ … ┆ LMM        ┆ G          ┆ G          ┆ false      │
│      ┆        ┆             ┆ 3dfa5f     ┆   ┆            ┆            ┆            ┆            │
└──────┴────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

#### For Individual answers

In [84]:
individual_models_answer_per_question = (
    (
        baseline_frame.with_columns(
            parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
        )
        .with_columns(
            pl.col("model_name").replace(MODEL_NAME_TO_LETTER_MAPPING),
            is_correct=comparer(
                pl.col(AnalysisColumn.parsed_answer.value), pl.col("answer_string")
            ),
        )
        .pivot(
            values="is_correct",
            index="question_id",
            on="model_name",
            aggregate_function="mean",
        )
    )
    .sort("question_id")
    .select("question_id", "L", "M", "H")
    .with_columns(pl.exclude("question_id").cast(bool))
)

individual_models_answer_per_question

shape: (100, 4)
┌─────────────┬───────┬───────┬───────┐
│ question_id ┆ L     ┆ M     ┆ H     │
│ ---         ┆ ---   ┆ ---   ┆ ---   │
│ i64         ┆ bool  ┆ bool  ┆ bool  │
╞═════════════╪═══════╪═══════╪═══════╡
│ 0           ┆ true  ┆ true  ┆ true  │
│ 1           ┆ true  ┆ false ┆ false │
│ 2           ┆ true  ┆ true  ┆ true  │
│ 3           ┆ false ┆ true  ┆ true  │
│ 4           ┆ false ┆ false ┆ true  │
│ …           ┆ …     ┆ …     ┆ …     │
│ 115         ┆ false ┆ false ┆ false │
│ 116         ┆ false ┆ false ┆ true  │
│ 117         ┆ false ┆ true  ┆ true  │
│ 118         ┆ false ┆ true  ┆ true  │
│ 119         ┆ false ┆ false ┆ false │
└─────────────┴───────┴───────┴───────┘

In [85]:
individual_models_answer_per_question.drop("question_id").corr()

shape: (3, 3)
┌──────────┬──────────┬──────────┐
│ L        ┆ M        ┆ H        │
│ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ 1.0      ┆ 0.371816 ┆ 0.230769 │
│ 0.371816 ┆ 1.0      ┆ 0.530859 │
│ 0.230769 ┆ 0.530859 ┆ 1.0      │
└──────────┴──────────┴──────────┘

--> Actually surprisingly different

In [86]:
df = pl.concat(
    [
        individual_models_answer_per_question.group_by(col)
        .agg(pl.all().exclude(col, "question_id").mean())
        .with_columns(
            pl.when(pl.col(col))
            .then(pl.lit(col + "_correct"))
            .otherwise(pl.lit(col + "_incorrect"))
            .alias("Given"),
            pl.when(pl.col(col)).then(pl.lit(1.0)).otherwise(pl.lit(0.0)).alias(col),
        )
        for col in individual_models_answer_per_question.columns
        if col != "question_id"
    ],
    how="diagonal",
)

df_single = df.select("Given", "L", "M", "H")

df_single

shape: (6, 4)
┌─────────────┬──────────┬──────────┬──────────┐
│ Given       ┆ L        ┆ M        ┆ H        │
│ ---         ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪══════════╪══════════╡
│ L_incorrect ┆ 0.0      ┆ 0.476923 ┆ 0.569231 │
│ L_correct   ┆ 1.0      ┆ 0.857143 ┆ 0.8      │
│ M_correct   ┆ 0.491803 ┆ 1.0      ┆ 0.852459 │
│ M_incorrect ┆ 0.128205 ┆ 0.0      ┆ 0.333333 │
│ H_correct   ┆ 0.430769 ┆ 0.8      ┆ 1.0      │
│ H_incorrect ┆ 0.2      ┆ 0.257143 ┆ 0.0      │
└─────────────┴──────────┴──────────┴──────────┘

-> They are not completely overlapping in the single answer case.

This means could be some diversity effect going on

---

In [87]:
individual_groups_answer_per_question = (
    (
        mad_analysis.filter(pl.col("group_constellation").str.len_chars() == 1).pivot(
            values="is_correct",
            index="question_id",
            on="group_constellation",
            aggregate_function="mean",
        )
    )
    .sort("question_id")
    .with_columns(pl.exclude("question_id").cast(bool))
)

df_single_mad = pl.concat(
    [
        individual_groups_answer_per_question.group_by(col)
        .agg(pl.all().exclude(col, "question_id").mean())
        .with_columns(
            pl.when(pl.col(col))
            .then(pl.lit(col + "_correct"))
            .otherwise(pl.lit(col + "_incorrect"))
            .alias("Given"),
            pl.when(pl.col(col)).then(pl.lit(1.0)).otherwise(pl.lit(0.0)).alias(col),
        )
        for col in individual_models_answer_per_question.columns
        if col != "question_id"
    ],
    how="diagonal",
).select("Given", "L", "M", "H")

df_single_mad

shape: (6, 4)
┌─────────────┬──────────┬──────────┬──────────┐
│ Given       ┆ L        ┆ M        ┆ H        │
│ ---         ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪══════════╪══════════╡
│ L_correct   ┆ 1.0      ┆ 0.884615 ┆ 0.923077 │
│ L_incorrect ┆ 0.0      ┆ 0.378378 ┆ 0.648649 │
│ M_correct   ┆ 0.45098  ┆ 1.0      ┆ 0.921569 │
│ M_incorrect ┆ 0.061224 ┆ 0.0      ┆ 0.510204 │
│ H_correct   ┆ 0.333333 ┆ 0.652778 ┆ 1.0      │
│ H_incorrect ┆ 0.071429 ┆ 0.142857 ┆ 0.0      │
└─────────────┴──────────┴──────────┴──────────┘

In [88]:
combined_ind = individual_models_answer_per_question.join(
    individual_groups_answer_per_question, on="question_id", suffix="_mad"
)
pl.concat(
    [
        combined_ind.group_by(col)
        .agg(pl.all().exclude(col, "question_id").mean())
        .with_columns(
            pl.when(pl.col(col))
            .then(pl.lit(col + "_correct"))
            .otherwise(pl.lit(col + "_incorrect"))
            .alias("Given"),
            pl.when(pl.col(col)).then(pl.lit(1.0)).otherwise(pl.lit(0.0)).alias(col),
        )
        for col in combined_ind.columns
        if col != "question_id"
    ],
    how="diagonal",
).select("Given", pl.exclude("Given"))

shape: (12, 7)
┌─────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Given           ┆ L        ┆ M        ┆ H        ┆ H_mad    ┆ M_mad    ┆ L_mad    │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str             ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ L_correct       ┆ 1.0      ┆ 0.857143 ┆ 0.8      ┆ 0.828571 ┆ 0.685714 ┆ 0.571429 │
│ L_incorrect     ┆ 0.0      ┆ 0.476923 ┆ 0.569231 ┆ 0.661538 ┆ 0.415385 ┆ 0.092308 │
│ M_correct       ┆ 0.491803 ┆ 1.0      ┆ 0.852459 ┆ 0.868852 ┆ 0.754098 ┆ 0.409836 │
│ M_incorrect     ┆ 0.128205 ┆ 0.0      ┆ 0.333333 ┆ 0.487179 ┆ 0.128205 ┆ 0.025641 │
│ H_correct       ┆ 0.430769 ┆ 0.8      ┆ 1.0      ┆ 0.892308 ┆ 0.661538 ┆ 0.353846 │
│ …               ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        │
│ H_mad_correct   ┆ 0.402778 ┆ 0.736111 ┆ 0.805556 ┆ 1.0      ┆ 0.652778 ┆ 0.333333 │
│ M_mad_incorrect ┆ 0.22449  ┆ 0.306122 ┆ 0.44898  ┆ 0.510204 ┆ 0.0      ┆ 0.061224 │
│ M_mad_correct   ┆ 0.470588 ┆ 0.901961 ┆ 0.843137 ┆ 0.921569 ┆ 1.0      ┆ 0.45098  │
│ L_mad_incorrect ┆ 0.202703 ┆ 0.486486 ┆ 0.567568 ┆ 0.648649 ┆ 0.378378 ┆ 0.0      │
│ L_mad_correct   ┆ 0.769231 ┆ 0.961538 ┆ 0.884615 ┆ 0.923077 ┆ 0.884615 ┆ 1.0      │
└─────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

> See Obsidian

#### Is the "nobody is right case" in HHH actually unanimous?

In [89]:
print("Answers where everyone was wrong:")

everyone_wrong = (
    mad_analysis.filter(pl.col("group_constellation") == "HHH")
    .explode(AnalysisColumn.parsed_individual_answers_before.value)
    .with_columns(
        is_individually_correct=comparer(
            pl.col(AnalysisColumn.parsed_individual_answers_before.value),
            pl.col("answer_string"),
        )
    )
    .group_by("question_id")
    .agg(
        number_wrong=pl.len(),
        answers=pl.col(AnalysisColumn.parsed_individual_answers_before.value).implode(),
        is_individually_correct=pl.col("is_individually_correct").implode(),
    )
    .filter(pl.col("is_individually_correct").list.eval(pl.element().not_()).list.all())
    .drop("number_wrong", "is_individually_correct")
)

print(everyone_wrong)
unanimous = (
    everyone_wrong["answers"]
    .filter(everyone_wrong["answers"].list.n_unique() == 1)
    .count()
)
print(f"Of that unanimous: {unanimous}")
print("Contentious:")
print(everyone_wrong["answers"].filter(everyone_wrong["answers"].list.n_unique() != 1))

Answers where everyone was wrong:
shape: (21, 2)
┌─────────────┬─────────────────────────────────┐
│ question_id ┆ answers                         │
│ ---         ┆ ---                             │
│ i64         ┆ list[str]                       │
╞═════════════╪═════════════════════════════════╡
│ 8           ┆ ["D", "D", "D"]                 │
│ 27          ┆ ["E", "E", "E"]                 │
│ 71          ┆ ["H", "H", "H"]                 │
│ 45          ┆ ["C", "C", "C"]                 │
│ 1           ┆ ["C", "C", "C"]                 │
│ …           ┆ …                               │
│ 46          ┆ ["D", "H", "D"]                 │
│ 11          ┆ ["___not_parsable___", "F", "_… │
│ 6           ┆ ["D", "D", "D"]                 │
│ 115         ┆ ["C", "C", "C"]                 │
│ 87          ┆ ["___not_parsable___", "___not… │
└─────────────┴─────────────────────────────────┘
Of that unanimous: 14
Contentious:
shape: (7,)
Series: 'answers' [list[str]]
[
	["B", "___not_parsable___", "B"]
	["E", "A", "___not_parsable___"]
	["D", "E", "E"]
	["C", "___not_parsable___", "___not_parsable___"]
	["C", "D", "C"]
	["D", "H", "D"]
	["___not_parsable___", "F", "___not_parsable___"]
]

C# Intra-Group Correctness Correlation (Aka group diversity)