In [1]:
import os
from collections import defaultdict
from itertools import chain

import polars as pl
from social_groups.analysis.defs.notebooks.definitions import register_materialization

from social_groups.analysis.polars_transformations import make_group_constellation
from social_groups.reporting.analysis_columns import AnalysisColumn
from social_groups.reporting.group_reply import (
    GroupReplyAggregator,
    MajorityVote,
    SingularityVote,
)
from social_groups.reporting.parsing import (
    AnswerOptions,
    AnswerParser,
    AnswerComparer,
)
from social_groups.directories import REPORTING_DIR
from social_groups.polars_values import MODEL_NAME_TO_LETTER_MAPPING
from social_groups.reporting.group_decision_scheme import calculate_decision_scheme

from social_groups.analysis.polars_transformations.apply_parsing_and_group_decision import (
    apply_parsing_and_group_decision,
)

%load_ext autoreload
%autoreload 2

In [2]:
output_dir = REPORTING_DIR / "heterogeneous_group"
os.makedirs(output_dir, exist_ok=True)

triple_underscore_handling = "wrong"

In [3]:
parser = AnswerParser(AnswerOptions.letters_A_to_J)
group_reply = GroupReplyAggregator(MajorityVote())
comparer = AnswerComparer(
    AnswerOptions.letters_A_to_J, triple_underscore_handling=triple_underscore_handling
)

## Analzying Basic Group Behaviour

In [4]:
from social_groups.analysis.definitions import defs

mad_frame = defs().load_asset_value("hetero_mad")
baseline_frame = defs().load_asset_value("baseline")
original_table_page46 = defs().load_asset_value(["report", "external", "group_problem_solving_page_46"])

/Users/philipp/Documents/Studium/Informatik/Masterthesis/Repository/.venv/lib/python3.11/site-packages/dagster/_config/pythonic_config/typing_utils.py:111: UserWarning: Field name "extension" in "PolarsParquetIOManager" shadows an attribute in parent "BasePolarsUPathIOManager"
  return super().__new__(cls, name, bases, namespaces, **kwargs)
2026-03-10 12:39:42 +0800 - dagster - DEBUG - system - Loading file from: /Users/philipp/Documents/Studium/Informatik/Masterthesis/Repository/results/analysis/dagster/hetero_mad.parquet using PolarsParquetIOManager...
2026-03-10 12:39:43 +0800 - dagster - DEBUG - system - Loading file from: /Users/philipp/Documents/Studium/Informatik/Masterthesis/Repository/results/analysis/dagster/baseline.parquet using PolarsParquetIOManager...
2026-03-10 12:39:43 +0800 - dagster - DEBUG - system - Loading file from: /var/folders/f0/f9gys8xx0psgwxr0dzsfp95h0000gn/T/tmpwyxemh93/storage/report/external/group_problem_solving_page_46 using PickledObjectFilesystemIOManager...

FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/f0/f9gys8xx0psgwxr0dzsfp95h0000gn/T/tmpwyxemh93/storage/report/external/group_problem_solving_page_46'

In [6]:
mad_frame.head()

shape: (5, 17)
┌──────┬────────┬─────────────┬─────────────┬───┬──────────┬─────────────┬────────────┬────────────┐
│ id   ┆ run_id ┆ question_id ┆ phoenix_spa ┆ … ┆ category ┆ question    ┆ answer_str ┆ model_name │
│ ---  ┆ ---    ┆ ---         ┆ n_id        ┆   ┆ ---      ┆ ---         ┆ ing        ┆ s          │
│ i64  ┆ i64    ┆ i64         ┆ ---         ┆   ┆ str      ┆ str         ┆ ---        ┆ ---        │
│      ┆        ┆             ┆ str         ┆   ┆          ┆             ┆ str        ┆ list[str]  │
╞══════╪════════╪═════════════╪═════════════╪═══╪══════════╪═════════════╪════════════╪════════════╡
│ 3260 ┆ 43     ┆ 5           ┆ 1aa14e4c915 ┆ … ┆ health   ┆ Q: What     ┆ J          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ cb1a3       ┆   ┆          ┆ stable      ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆             ┆   ┆          ┆ isotope is  ┆            ┆            │
│      ┆        ┆             ┆             ┆   ┆          ┆ comm…       ┆            ┆            │
│ 3261 ┆ 43     ┆ 6           ┆ c0ea9a68165 ┆ … ┆ physics  ┆ Q: An       ┆ I          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ ac33e       ┆   ┆          ┆ electric    ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆             ┆   ┆          ┆ dipole      ┆            ┆            │
│      ┆        ┆             ┆             ┆   ┆          ┆ consisti…   ┆            ┆            │
│ 3262 ┆ 43     ┆ 0           ┆ 6bc64c3c961 ┆ … ┆ other    ┆ Q: In 2018, ┆ G          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ beda7       ┆   ┆          ┆ about how   ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆             ┆   ┆          ┆ many chi…   ┆            ┆            │
│ 3263 ┆ 43     ┆ 8           ┆ 35ee8080254 ┆ … ┆ law      ┆ Q: A        ┆ E          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ 89b27       ┆   ┆          ┆ company     ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆             ┆   ┆          ┆ contracted  ┆            ┆            │
│      ┆        ┆             ┆             ┆   ┆          ┆ with a…     ┆            ┆            │
│ 3264 ┆ 43     ┆ 2           ┆ ee9c12870a3 ┆ … ┆ physics  ┆ Q: Kirkwood ┆ F          ┆ ["Qwen/Qwe │
│      ┆        ┆             ┆ b979e       ┆   ┆          ┆ gaps are    ┆            ┆ n3-14B"]   │
│      ┆        ┆             ┆             ┆   ┆          ┆ observed …  ┆            ┆            │
└──────┴────────┴─────────────┴─────────────┴───┴──────────┴─────────────┴────────────┴────────────┘

In [7]:
# TODO: Is this mixed for different datasets? (MAD-> subset, Baseline -> Full Eval?)
baseline_analysis = (
    baseline_frame.with_columns(
        parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
    )
    .with_columns(
        is_correct=comparer(
            pl.col(AnalysisColumn.parsed_answer.value), pl.col("answer_string")
        )
    )
    .group_by("model_name")
    .agg(accuracy=pl.col("is_correct").mean())
)

In [8]:
model_name_sort = {
    "Qwen/Qwen3-14B": 1,
    "Qwen/Qwen3-4B": 2,
    "Qwen/Qwen3-0.6B": 3,
}

mad_analysis = apply_parsing_and_group_decision(
    mad_frame, parser, comparer, group_reply
).with_columns(make_group_constellation())

table_page_46 = pl.concat(
    [
        (
            mad_analysis.group_by("group_constellation")
            .agg(accuracy=pl.col("is_correct").mean())
            .with_columns(origin=pl.lit("(MAD)"))
        ),
        (
            baseline_analysis.with_columns(
                group_constellation=pl.col("model_name").replace(
                    MODEL_NAME_TO_LETTER_MAPPING
                ),
            ).with_columns(origin=pl.lit("(baseline)"))
        ),
    ],
    how="diagonal",
)

register_materialization("heterogeneous_groups_evaluation_table", table_page_46, "The main evaluation of different group constellations for Multi Agent Debate, can be nicely compared to the table on page 46 of Group Problem Solving Book.")
table_page_46

shape: (37, 4)
┌─────────────────────┬──────────┬────────────┬─────────────────┐
│ group_constellation ┆ accuracy ┆ origin     ┆ model_name      │
│ ---                 ┆ ---      ┆ ---        ┆ ---             │
│ str                 ┆ f64      ┆ str        ┆ str             │
╞═════════════════════╪══════════╪════════════╪═════════════════╡
│ M                   ┆ 0.55     ┆ (MAD)      ┆ null            │
│ HL                  ┆ 0.53     ┆ (MAD)      ┆ null            │
│ LLLM                ┆ 0.61     ┆ (MAD)      ┆ null            │
│ LL                  ┆ 0.28     ┆ (MAD)      ┆ null            │
│ HM                  ┆ 0.65     ┆ (MAD)      ┆ null            │
│ …                   ┆ …        ┆ …          ┆ …               │
│ HLL                 ┆ 0.46     ┆ (MAD)      ┆ null            │
│ HHHM                ┆ 0.67     ┆ (MAD)      ┆ null            │
│ H                   ┆ 0.64     ┆ (baseline) ┆ Qwen/Qwen3-14B  │
│ L                   ┆ 0.35     ┆ (baseline) ┆ Qwen/Qwen3-0.6B │
│ M                   ┆ 0.59     ┆ (baseline) ┆ Qwen/Qwen3-4B   │
└─────────────────────┴──────────┴────────────┴─────────────────┘

In [9]:
original_table_page46

shape: (13, 2)
┌─────────────────────┬─────────────────────┐
│ group_constellation ┆ score (-115 to 115) │
│ ---                 ┆ ---                 │
│ str                 ┆ i64                 │
╞═════════════════════╪═════════════════════╡
│ HHH                 ┆ 80                  │
│ HHM                 ┆ 74                  │
│ HHL                 ┆ 67                  │
│ HML                 ┆ 64                  │
│ HMM                 ┆ 61                  │
│ …                   ┆ …                   │
│ M                   ┆ 42                  │
│ MML                 ┆ 39                  │
│ MLL                 ┆ 37                  │
│ L                   ┆ 25                  │
│ LLL                 ┆ 21                  │
└─────────────────────┴─────────────────────┘

In [10]:
decision_schemes = (
    mad_analysis.group_by("group_constellation")
    .map_groups(
        lambda g: calculate_decision_scheme(
            g,
            AnalysisColumn.parsed_individual_answers_before.value,
            AnalysisColumn.parsed_individual_answers_after.value,
            "answer_string",
            group_reply,
            comparer,
        ).select(
            pl.lit(g["group_constellation"].unique().item()).alias(
                "group_constellation"
            ),
            "Correct Members Beginning",
            "correct",
            "incorrect",
        )
    )
    .sort("group_constellation")
)

decision_schemes.write_csv(output_dir / "group_decision_schemes.csv")

decision_schemes

shape: (139, 4)
┌─────────────────────┬───────────────────────────┬──────────┬───────────┐
│ group_constellation ┆ Correct Members Beginning ┆ correct  ┆ incorrect │
│ ---                 ┆ ---                       ┆ ---      ┆ ---       │
│ str                 ┆ u32                       ┆ f64      ┆ f64       │
╞═════════════════════╪═══════════════════════════╪══════════╪═══════════╡
│ H                   ┆ 1                         ┆ 0.986111 ┆ 0.013889  │
│ H                   ┆ 0                         ┆ 0.142857 ┆ 0.857143  │
│ HH                  ┆ 2                         ┆ 1.0      ┆ 0.0       │
│ HH                  ┆ 1                         ┆ 0.6875   ┆ 0.3125    │
│ HH                  ┆ 0                         ┆ 0.181818 ┆ 0.818182  │
│ …                   ┆ …                         ┆ …        ┆ …         │
│ MMMM                ┆ 4                         ┆ 0.925926 ┆ 0.074074  │
│ MMMM                ┆ 3                         ┆ 0.666667 ┆ 0.333333  │
│ MMMM                ┆ 2                         ┆ 0.666667 ┆ 0.333333  │
│ MMMM                ┆ 1                         ┆ 0.571429 ┆ 0.428571  │
│ MMMM                ┆ 0                         ┆ 0.060606 ┆ 0.939394  │
└─────────────────────┴───────────────────────────┴──────────┴───────────┘

## Unparsable answers:

In [11]:
unparsable_answers_per_model = defaultdict(int)

### In the baseline:

In [12]:
for answer in (
    baseline_frame.with_columns(
        parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
    )
    .filter(pl.col(AnalysisColumn.parsed_answer.value).str.starts_with("___"))
    .select(["final_answer", "model_name"])
    .iter_rows()
):
    print(answer[1], ": \n")
    print(answer[0][-150:])
    print("-" * 50)
    unparsable_answers_per_model[answer[1]] += 1

Qwen/Qwen3-4B :

sec². So, if I have h1 - h2 in Btu/lbm, I need to convert it to ft²/sec². Let me use the following conversion:

1 Btu/lbm = 778.169 ft-lbf/lbm

Then,
--------------------------------------------------
Qwen/Qwen3-4B :

rsible expansion of an ideal gas, the relation between temperature and pressure is given by $ T_2 = T_1 \left( \frac{P_2}{P_1} \right)^{\frac{\gamma -
--------------------------------------------------
Qwen/Qwen3-0.6B :

 maybe the velocity coefficient is used with the discharge coefficient. Let me check the formula again.

Alternatively, maybe the velocity coefficient
--------------------------------------------------
Qwen/Qwen3-0.6B :

1^{2/3}) $

But since $ T_1 = \frac{P_1 V_1}{n R} $, and $ T_2 = \frac{P_2 V_2}{n R} $, we can express $ V_2^{2/3} $ in terms of $ V_1 $:

From the ad
--------------------------------------------------
Qwen/Qwen3-14B :

tate this exactly. However, Option A says "If it's not the case that both Izzy plays Minecraft and Ashleigh stops by then Russell makes dinner." Which
--------------------------------------------------
Qwen/Qwen3-14B :

hout knowing B, this is not helpful. Alternatively, the splitting in terms of magnetic field is ΔB = A / (g_e * μ_B / ħ). But again, without knowing A
--------------------------------------------------
Qwen/Qwen3-4B :

citly convert $ M $ to a real. In FORTRAN, `EXP(-M)` would implicitly convert the integer $ M $ to a real, and `M ** X` is valid for integer exponents
--------------------------------------------------
Qwen/Qwen3-4B :

.

Alternatively, maybe the problem is using the value of Cv for CO2 as 25.1 J/mol·K.

Alternatively, maybe the problem is using the value of Cv for
--------------------------------------------------
Qwen/Qwen3-4B :

 annual interest rate as (Total Interest / Principal) * (12 / 12) * 100, but that's the same as before.

Alternatively, maybe the problem is using the
--------------------------------------------------
Qwen/Qwen3-4B :

ke in the calculation of Y.

Wait, maybe the savings identity is S = I + (X - M) + (G - T)? No, that's not correct. The correct identity is S = I + (X
--------------------------------------------------
Qwen/Qwen3-4B :

the resolution is 200 cycles/mm, then:

200 = D / (2.43 * f)

Solving for D:

D = 200 * 2.43 * f

Given that f is 50 mm, then:

D = 200 * 2.43 * 50 =
--------------------------------------------------
Qwen/Qwen3-14B :

hould equal thickness. However, option D has thickness = 0.5 in and width = 0.75 in, which is not a square key. Therefore, this option is invalid. The
--------------------------------------------------
Qwen/Qwen3-14B :

. Still not matching the options. The options are around 2.1 to 2.3 degrees. Hmm.

Wait, maybe I made a mistake in the lattice parameter. Let me check
--------------------------------------------------
Qwen/Qwen3-14B :

vapor pressure data at that temperature.

This seems like a dead end. Let me go back to the earlier calculation for ΔH_fus. If I assumed ΔP ≈ 1 atm, I
--------------------------------------------------
Qwen/Qwen3-0.6B :

rization. The standard formula is:

ΔH_vap = (mass of the substance) × (ΔT) × (R × 1000) / (1000 × 1000) ?

No, that's not correct. Let me think again
--------------------------------------------------
Qwen/Qwen3-0.6B :

tion is the product of the marginal distributions. So, if X, Y, Z are jointly Gaussian, then their variances are not necessarily equal. However, since
--------------------------------------------------
Qwen/Qwen3-0.6B :

k once more. The total amount is $490, which is 450 + 40. So the interest is 40. The rate is 40/(450*12). Let me check if 40 is 17.5% of 450. 17.5% of
--------------------------------------------------
Qwen/Qwen3-4B :

iter (option A). But the options here are (A) three times that of Jupiter (so 3:1 ratio), which would be a 1:3 ratio. That's not a resonance. Wait, no
--------------------------------------------------
Qwen/Qwen3-4B :

netic field. The formula for the hyperfine splitting is:

ΔB = (Δf) / (giso)

But if Δf is 500 MHz, then:

ΔB = 500 / 2.12 ≈ 235.8 T. But that's 235,8
--------------------------------------------------
Qwen/Qwen3-0.6B :

thickness = 1/2 in., width = 3/4 in., length = 2.5 in. So that's a square key with 1/2 in thickness and 1/2 in width, and 2.5 in length. But the shaft
--------------------------------------------------
Qwen/Qwen3-0.6B :

on again. The two times are 6:12:43 and 6:52:43. The difference is 40 minutes. So if he left at 6:12:43, he was away for 40 minutes. But since he left
--------------------------------------------------
Qwen/Qwen3-0.6B :

me 30. So, real GDP is $30. Let me look at the options. Option G is $30. That makes sense. So the answer should be G.
</think>

The answer is ... (G).
--------------------------------------------------
Qwen/Qwen3-0.6B :

ybe there's a mistake in the options? Or perhaps I misread the problem.

Wait, looking back at the options, (D) is 3.6°C/s. Let me check if there's a
--------------------------------------------------
Qwen/Qwen3-14B :

X,Z) = 0.1 * 0.9 = 0.09.

Then, the mutual information between X and Z is (1/2) log(1/(1 - ρ²(X,Z))) = (1/2) log(1/(1 - 0.09²)) = (1/2) log(1/(1 - 0.0
--------------------------------------------------
Qwen/Qwen3-14B :

ely, perhaps the problem is not using the national income identity but another approach. Let me think again. The question is about the current deficit
--------------------------------------------------
Qwen/Qwen3-4B :

ng = T / (r * w * L)

So, solving for w from shear: w² = T / (r * τ_shear)

Solving for L from bearing: L = T / (r * τ_bearing * w)

But since w is
--------------------------------------------------
Qwen/Qwen3-4B :

a mistake in the calculation of the angle. Let me check again.

If d = 3.95 Å, λ = 0.248 Å.

Then sinθ = λ / (2d) = 0.248 / (2 * 3.95) = 0.248 / 7.9
--------------------------------------------------
Qwen/Qwen3-4B :

erature. But again, without knowing the critical pressure, this is not helpful.

Alternatively, maybe we can use the fact that the triple point is at
--------------------------------------------------
Qwen/Qwen3-0.6B :

he other options don't address the government's right to protect the informant's identity. So the answer should be G.
</think>

The answer is ... (G).
--------------------------------------------------

## In the MAD:

In [13]:
for answer in chain(
    mad_analysis.filter(
        pl.col(AnalysisColumn.parsed_individual_answers_before.value)
        .list.eval(pl.element().str.starts_with("___"))
        .list.any()
    )
    .select(
        "answers_at_beginning",
        AnalysisColumn.parsed_individual_answers_before.value,
        "model_names",
    )
    .iter_rows(),
    mad_analysis.filter(
        pl.col(AnalysisColumn.parsed_individual_answers_before.value)
        .list.eval(pl.element().str.starts_with("___"))
        .list.any()
    )
    .select(
        "answers_at_end",
        AnalysisColumn.parsed_individual_answers_after.value,
        "model_names",
    )
    .iter_rows(),
):
    for i, parsed in enumerate(answer[1]):
        if parsed.startswith("___"):
            unparsable_answers_per_model[answer[2][i]] += 1
            print(parsed, f"from {answer[2][i]}: \n")
            print(answer[0][i][-150:])
            print("-" * 50)

___not_parsable___ from Qwen/Qwen3-0.6B:

decay. Yes, that makes sense. So the answer should be E.
</think>

The tendency for migration to decrease with distance is called (E): distance decay.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

nd up. Therefore, the new waist size is 36 inches.

Looking at the options, option A is 36 inches. So the answer should be A.
</think>

A: 36 inches.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 of products would be N2 : H2 : 2NH. But since the rate constants are given, we need to find the ratio based on the given k_a/k_b/k_c.

Alternatively
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

, maybe the current deficit is $18.07 billion, which would be option A. But I can't see why. Alternatively, maybe I made a mistake in the calculation.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

X and Z is equal to the covariance between X and Z multiplied by the logarithm of the ratio of the variances. Wait, no, that's not correct. The mutual
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

options again. Wait, maybe the total amount paid is $1840, and the down payment is $50, so the interest is $1790. Then, the interest rate is (1790 / 1
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 h), where h is the head in meters. Let's try with h = 0.1 m.

V = 0.95 * 0.92 * sqrt(2 * 9.81 * 0.1) ≈ 0.95 * 0.92 * sqrt(1.962) ≈ 0.95 * 0.92 * 1.4
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ħ^2) / (μ_0 * 4π * r^3) * something. But without knowing r, this is not helpful.

Alternatively, the hyperfine splitting in terms of magnetic field is
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 Converting to ft²/sec², since 1 ft·lbf = 32.174 ft²/sec², so R = 85.78 * 32.174 ≈ 2760 ft²/sec²·°R.

Temperature T1 is 600°F, which is 600 + 459.67 =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

/ π

So:

500e6 = (2.12 * 2.8025e8 * B) / π

Solving for B:

B = (500e6 * π) / (2.12 * 2.8025e8) ≈ (1.57e9) / (5.93e8) ≈ 2.65 T

Still too large. This
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

qrt(5,007,200) ≈ 2238 ft/s. Then, applying the coefficients: 2238 * 0.92 * 0.95 ≈ 1955 ft/s. But this is not in the options. However, option E is 3697
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

0 V.

So hc = 6.626e-34 * 3e8 = 1.9878e-25 J·m. eV = 1.602e-19 * 5e4 = 8.01e-15 C·V. Then λ_min = 1.9878e-25 / 8.01e-15 ≈ 2.48e-11 m = 0.0248 nm = 0.2
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

erefore, the answer should be (A).
</think>

(A): If it's not the case that both Izzy plays Minecraft and Ashleigh stops by then Russell makes dinner.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

t I'm not 100% sure. However, based on my knowledge, 250 billion is a plausible number for chicken meat production in 2018.
</think>

(A): 250 billion
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

units are consistent, and the calculation seems right. So the correct option is (I).
</think>

(A): $9.30 \times 10^{-15} \mathrm{C} \cdot \mathrm{m}$
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

rom different centuries, like the early 4th century BCE, which might be too early. The answer should be (C).
</think>

A: (C) Early Fifth Century BCE.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

t budget deficit plus the difference in tax revenues and government spending due to the change in GNP.

But how?

Alternatively, the full employment
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 planes. Then d = a / sqrt(2) ≈ 6.29 / 1.414 ≈ 4.45 Å. Then:

sinθ = 0.248 / (2 * 4.45) ≈ 0.248 / 8.9 ≈ 0.0279

θ ≈ 1.6 degrees. Still not matching.


--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

, according to the derivation, they are the same. Therefore, the key is designed based on shear stress.

So the options that satisfy τ ≤ 11,000 are B
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

ifferent value for the specific enthalpy difference. For example, if the specific enthalpy difference is 1000 Btu/lbm, then the ideal velocity is sqrt
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

 suggests that my approach is wrong.

Wait, maybe the formula is different. The hyperfine splitting in EPR is given by the formula:

Δ = (giso * γ * B
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

y. Alternatively, the splitting is given by:

Δf = (giso * μ_N * B) / (h * 2π)

But the splitting is 500 MHz, which is the splitting between the lines
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

ate for each option:

Option A: thickness = 1/2 in., width = 1/2 in., length = 3 in.

x = 1/2 in. (since width and thickness are same)

L = 3 in.

So,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

1e-9 m is 10 Å. So 1.355e-9 m is 13.55 Å. But the correct lattice parameter is 6.29 Å. So there's a contradiction here.

Wait, this is confusing. Let
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

 So 1.35 * 4.67e-10 ≈ 6.30e-10 m, which is 6.30 Å. So that's correct.

So with d = a = 6.30 Å, and λ = 0.248 Å, then sinθ = 0.248 / (2 * 6.30) = 0.248
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

e function is declared as INTEGER X, but the code uses Y = FLOAT(M), which is a real. Then P is assigned a real value. But the function is declared as
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

alories. So 730,000 / 0.49 = 1,489,796 grams. But that's 1,489.8 kg. However, the per day calculation gives 14.9 kg. So there's a factor of 100 error.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

076e23)

Calculate numerator: 4 * 0.0746 = 0.2984 kg/mol

Denominator: 1.99e3 * 6.02214076e23 = 1.99 * 6.02214076e26 ≈ 11.984e26 kg/(m³·mol)

So a³ =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ation. Let me check the calculation again.

Wait, the formula for density is ρ = (Z * M) / (N_A * a³). Let me plug in the numbers again:

Z = 4
M = 74
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

hat both shear and bearing stresses are exactly at the allowable limits.

Let me set up the equations again:

From shear stress: τ = (T / r) / (t²) =
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

allowable 22,000 psi. So that's okay. So option (C) would be acceptable. But earlier when I calculated using the shear stress formula τ = F / A, I got
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

8.0 × 10^-14 cal.

Then, power is current (4.8 × 10^-6 A) multiplied by energy per proton (8.0 × 10^-14 cal/A) = 4.8 × 10^-6 * 8.0 × 10^-14 = 3.84 ×
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

think>

A: (H) A central planning committee allocates resources in the Soviet economy, while supply and demand dictate allocation in a market economy.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 = 40.123 mT = 1.09876 cm⁻¹

(C): 500 MHz = 16.850 mT = 0.01667 cm⁻¹

(D): 500 MHz = 45.672 mT = 2.86329 cm⁻¹

(E): 500 MHz = 70.456 mT = 4.32109 cm⁻¹
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

yperosmolality and potassium/lactate levels are more about fluid balance. So, the correct answer should be C.
</think>

(A): An excess of lactic acid.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

7.2 million = $107.2 million. But the builder said they agreed to increase to $101 million. That's a $6.2 million increase. That seems like a big jump
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

ich is the ratio between the actual velocity and the velocity in the nozzle.

So, if the theoretical velocity is v, then the actual velocity is v * 0
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

raft and Ashleigh stops by then Russell makes dinner." This is confusing. If it's "both not the case that Izzy plays Minecraft and Ashleigh stops by,"
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

Therefore, the answer should be A.
</think>

(A): If it's not the case that both Izzy plays Minecraft and Ashleigh stops by then Russell makes dinner.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ocity in terms of the pressure and the specific volume. For an isentropic process, the enthalpy change can be related to the pressure change. However,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

.7-0.8 in², and exit area around 8-9 in². If the mass flow rate is 12,000 lb/hr, and the velocity at the throat is around 3697 ft/sec (from option E),
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

/ (J/T·Hz) = (J·s·T) / (J/T·Hz) = (s·T²)/Hz.

But this doesn't seem to give the right units for A. I think I'm making a mistake in the formula. Let me
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

it, but the options are in eV. Wait, maybe the question is wrong. Alternatively, maybe I made a mistake in the formula. Let me think again. The recoil
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

τ = F / (L * t). Let's try that.

For option (C): L = 2 in, t = 1 in. So shear area = 2 * 1 = 2 in². τ = 20,000 / 2 = 10,000 psi, which is below 11,00
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

290 / 5.5 = 52.727 minutes

So the times are approximately 12.727 and 52.727 minutes after 6 p.m. Since he returned before 7 p.m., which is 60 minutes
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

and it's 2 M, then the moles should be 2 times 3, which is 6. Let me check the options. Option C is 6. So the answer should be C.
</think>

(A): 6 mol
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

. For (110), d = a / sqrt(1² + 1² + 0²) = a / sqrt(2) ≈ 6.29 / 1.414 ≈ 4.45 Å. Then sinθ = 0.248 / (2 * 4.45) ≈ 0.248 / 8.9 ≈ 0.0279, θ ≈ 1.6 degrees.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

N_A.

But since the crystal is cubic, the number of ions per unit volume is also equal to the number of K+ ions per unit volume plus the number of Cl
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

g to real is not necessary. However, the formula requires m^x, which is a real number. Therefore, the code should convert M to a real. But in option B
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 that. Wait, maybe the options are written with different variables. For example, maybe option A is correct. Let me check again.

Option A: EXP(M) * M
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

nd up. Therefore, the new waist size is 36 inches.

Looking at the options, option A is 36 inches. So the answer should be A.
</think>

A: 36 inches.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 math: 6000 divided by 200 is 30. So, real GDP should be $30. Looking at the options, option G is $30. So the answer should be G.
</think>

A: (G) $30
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

* ∆V)] * (-0.02 K)

So:

P_triple = 1 atm - [∆H_fus / (T * ∆V)] * 0.02 K

Let's recalculate with this corrected sign.

Using option B: ∆H_fus=1.5 kcal
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

limation (∆H_S) = ∆H_vap + ∆H_fus ≈ 11.35 kcal/mol.

3. **Vapor Pressure at the Triple Point (P_1):**
   Using the Clausius-Clapeyron equation for
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

/mol. If the specific heat is 0.2 Btu/(lb·°R), then Q = 0.2 * 0.09699 * 3000 ≈ 58.2 Btu. Still not matching.

This is really puzzling. The options are
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ound interest. Let's compute (1.0155)^12:

We can use the formula (1 + r)^n = e^{n * ln(1 + r)}.

ln(1.0155) ≈ 0.01537 (as before). Multiply by 12: 0.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

λ = 550e-6 mm, f = 50 mm:

D = 200 * 550e-6 * 50

Calculate:

550e-6 * 50 = 0.0275

Multiply by 200: 0.0275 * 200 = 5.5 mm

So D = 5.5 mm. The options
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

). If the correlation between X and Z is ρ1*ρ2, then that formula applies. But in the example where ρ1=0.5 and ρ2=0.5, the mutual information would be
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

on. But this isn't an option. The options given are (A) $18.07, (B) $12.5, etc. So this suggests that my approach is incorrect.

Wait, maybe I need to
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

 However, the options given are (A) $18.07, (B) $12.5, etc. So, this suggests that my assumption about the savings rate is incorrect.

Alternatively,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

jet in terms of the specific enthalpy, but I'm missing something.

Alternatively, maybe the problem is using the specific enthalpy in different units.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

nswer options are given as permutations of the rate constants. Therefore, the answer is the ratio of the rate constants. But the problem is not clear.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

rect code must have P as a real. But in the options, the function is declared as INTEGER X, M. So that's not correct. Therefore, the correct code must
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

n B and D?

Wait, the problem says that the function is to compute P(X) = e^{-m} * m^x / x!.

In option B, the code is using M as an integer. So EXP(-
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

sts that the problem might have a mistake, or I'm missing something.

Wait, perhaps the formula for shear stress is different. Let me think again. The
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

tress: τ_shear = 30,000 / (2 * 1 * 1.5) = 30,000 / 3 = 10,000 psi. This is less than 11,000. So shear is okay.

Bearing stress: same as shear stress,
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

ad before.

Wait, maybe the formula is τ = T / (b * t * L). Let me check that.

If that's the case, then for option C: τ = 30,000 / (1 * 1 * 2) = 15
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

efore, the U.S. net exports would be (lower exports) - (lower imports). If the U.S. exports to Japan decrease by a certain amount and the U.S. imports
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-4B:

depreciate.

But that's not an option. However, looking at the options, option (H) is Decreases, Decreases, Decreases. That would mean the dollar and
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

ion FACT(n) is available, which returns an integer. So the code in option B would be EXP(-M) * (M**X) / FACT(X). If M is integer, then M**X is integer
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 math: 6000 divided by 200 is 30. So, real GDP should be $30. Looking at the options, option G is $30. So the answer should be G.
</think>

A: (G) $30
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

 that the determinant is equal to the product of the diagonal entries.

Alternatively, maybe we can find that the determinant is equal to the product
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

Yes, distance decay is when the distance between people increases, making it harder to move. So the answer should be E.
</think>

(A): distance decay.
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

is 0.02 K. The molar volume difference is 4.412 × 10^-6 m³/mol. Let's assume that the pressure change ΔP is small, so we can use the approximation:

Δ
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

en the triple point and the critical point, but again, without the critical pressure, this is not possible.

This is quite challenging. However, given
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

= (molar mass) × (ΔT) × (L_v / molar mass)

But I need to find the correct value. Let me check the standard approach. The enthalpy of vaporization can
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

fic heat capacity in terms of Btu per pound-mass, but the mass is in pounds. Let me check the specific heat of CO2 in Btu/(lb·°F) again. If it's 0.201
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

60,000 Btu. But where would that specific heat value come from?

Alternatively, maybe the problem is using the specific heat in terms of Btu per pound
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

information between two jointly Gaussian variables is given by:

I(X;Z) = (1/2) log(1/(1 - ρ²)) bits, where ρ is the correlation coefficient between X
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-0.6B:

covariance between X and Y and the covariance between Y and Z multiplied by the correlation coefficient between X and Z. But that would be if they are
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:

^5 ≈ 1.0653 * 1.016 ≈ 1.0822

1.016^6 ≈ 1.0822 * 1.016 ≈ 1.0993

1.016^7 ≈ 1.0993 * 1.016 ≈ 1.1166

1.016^8 ≈ 1.1166 * 1.016 ≈ 1.1341

1.016^9 ≈ 1.134
--------------------------------------------------
___not_parsable___ from Qwen/Qwen3-14B:


-> Qwen 0.6B often says "Answer should be A /think. The Answer is G"

In [14]:
unparsable_answers_per_model

defaultdict(int,
            {'Qwen/Qwen3-4B': 376,
             'Qwen/Qwen3-0.6B': 856,
             'Qwen/Qwen3-14B': 317})

### Build an overview of parsing error Influence

In [15]:
baseline_frame_with_group_constellation = baseline_frame.with_columns(
    group_constellation=pl.col("model_name").replace(MODEL_NAME_TO_LETTER_MAPPING)
    + pl.lit(" (Baseline)")
).drop("model_name")

parsing_error_influence_table = pl.DataFrame(
    {
        "group_constellation": mad_analysis["group_constellation"]
        .unique()
        .extend(baseline_frame_with_group_constellation["group_constellation"].unique())
        .sort()
    }
)

for handling in ["null", "wrong", "random"]:
    new_comparer = AnswerComparer(AnswerOptions.letters_A_to_J, handling)

    new_mad = (
        apply_parsing_and_group_decision(mad_frame, parser, new_comparer, group_reply)
        .with_columns(make_group_constellation())
        .group_by("group_constellation")
        .agg(accuracy=pl.col("is_correct").mean())
    )

    new_base = (
        baseline_frame_with_group_constellation.with_columns(
            parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
        )
        .with_columns(
            is_correct=new_comparer(
                pl.col(AnalysisColumn.parsed_answer.value), pl.col("answer_string")
            )
        )
        .group_by("group_constellation")
        .agg(accuracy=pl.col("is_correct").mean())
    )

    parsing_error_influence_table = parsing_error_influence_table.join(
        pl.concat([new_mad, new_base], how="diagonal").select(
            "group_constellation",
            pl.col("accuracy").alias(f"Accuracy ({handling})"),
        ),
        on="group_constellation",
        how="inner",
    )

parsing_error_influence_table.with_columns(
    deviation=(
        pl.max_horizontal(pl.exclude("group_constellation"))
        - pl.min_horizontal(pl.exclude("group_constellation"))
    ).alias("range")
)

shape: (37, 5)
┌─────────────────────┬─────────────────┬──────────────────┬───────────────────┬───────────┐
│ group_constellation ┆ Accuracy (null) ┆ Accuracy (wrong) ┆ Accuracy (random) ┆ deviation │
│ ---                 ┆ ---             ┆ ---              ┆ ---               ┆ ---       │
│ str                 ┆ f64             ┆ f64              ┆ f64               ┆ f64       │
╞═════════════════════╪═════════════════╪══════════════════╪═══════════════════╪═══════════╡
│ M                   ┆ 0.597826        ┆ 0.55             ┆ 0.57              ┆ 0.047826  │
│ LM                  ┆ 0.616279        ┆ 0.53             ┆ 0.54              ┆ 0.086279  │
│ HHHM                ┆ 0.683673        ┆ 0.67             ┆ 0.68              ┆ 0.013673  │
│ L                   ┆ 0.247312        ┆ 0.23             ┆ 0.23              ┆ 0.017312  │
│ HHHH                ┆ 0.721649        ┆ 0.7              ┆ 0.71              ┆ 0.021649  │
│ …                   ┆ …               ┆ …                ┆ …                 ┆ …         │
│ HHM                 ┆ 0.714286        ┆ 0.7              ┆ 0.7               ┆ 0.014286  │
│ HM                  ┆ 0.691489        ┆ 0.65             ┆ 0.65              ┆ 0.041489  │
│ M (Baseline)        ┆ 0.670455        ┆ 0.59             ┆ 0.6               ┆ 0.080455  │
│ H (Baseline)        ┆ 0.688172        ┆ 0.64             ┆ 0.64              ┆ 0.048172  │
│ L (Baseline)        ┆ 0.388889        ┆ 0.35             ┆ 0.36              ┆ 0.038889  │
└─────────────────────┴─────────────────┴──────────────────┴───────────────────┴───────────┘

-> Using (null) is the best, as unparsed values increase your score... should not be used

-> Using wrong is the worst, could possibly be used to be fair, as it is "not correct"

-> Papers and Benchmarks often use "random", which increases the values artificially and introduces noise.. I do not like it, but to be fair one should use it.

---

-> But in all of out cases, even absolute deviation is actually pretty low. (it gets mitigated in group decisions, as unparsable values are ignored in aggregation)

# Agreeableness -> Number of Cases where they reach conslusion

In [16]:
unanimity = (
    mad_analysis.with_columns(
        pl.col(AnalysisColumn.parsed_individual_answers_after.value)
        .list.n_unique()
        .eq(1)
        .alias("End unanimity"),
        pl.col(AnalysisColumn.parsed_individual_answers_before.value)
        .list.n_unique()
        .eq(1)
        .alias("Start unanimity"),
    )
    .group_by("group_constellation")
    .agg(
        pl.col("End unanimity").mean(),
        pl.col("Start unanimity").mean(),
        pl.when(pl.col("Start unanimity"))
        .then(None)
        .otherwise(pl.col("End unanimity"))
        .mean()
        .alias("End Unanimity | not Start Unanimity"),
        pl.when(pl.col("Start unanimity"))
        .then(pl.col("End unanimity"))
        .otherwise(None)
        .mean()
        .alias("End Unanimity | Start Unanimity"),
        accuracy=pl.col("is_correct").mean(),
    )
)

unanimity

shape: (34, 6)
┌─────────────────┬───────────────┬─────────────────┬─────────────────┬─────────────────┬──────────┐
│ group_constella ┆ End unanimity ┆ Start unanimity ┆ End Unanimity | ┆ End Unanimity | ┆ accuracy │
│ tion            ┆ ---           ┆ ---             ┆ not Start Unan… ┆ Start Unanimit… ┆ ---      │
│ ---             ┆ f64           ┆ f64             ┆ ---             ┆ ---             ┆ f64      │
│ str             ┆               ┆                 ┆ f64             ┆ f64             ┆          │
╞═════════════════╪═══════════════╪═════════════════╪═════════════════╪═════════════════╪══════════╡
│ HHHM            ┆ 0.92          ┆ 0.64            ┆ 0.833333        ┆ 0.96875         ┆ 0.67     │
│ LLLL            ┆ 0.76          ┆ 0.3             ┆ 0.7             ┆ 0.9             ┆ 0.26     │
│ HHHL            ┆ 0.7           ┆ 0.24            ┆ 0.644737        ┆ 0.875           ┆ 0.64     │
│ LM              ┆ 0.79          ┆ 0.32            ┆ 0.764706        ┆ 0.84375         ┆ 0.53     │
│ HLMM            ┆ 0.82          ┆ 0.21            ┆ 0.772152        ┆ 1.0             ┆ 0.62     │
│ …               ┆ …             ┆ …               ┆ …               ┆ …               ┆ …        │
│ HL              ┆ 0.72          ┆ 0.33            ┆ 0.61194         ┆ 0.939394        ┆ 0.53     │
│ HHHH            ┆ 0.98          ┆ 0.72            ┆ 0.928571        ┆ 1.0             ┆ 0.7      │
│ HMMM            ┆ 0.93          ┆ 0.72            ┆ 0.928571        ┆ 0.930556        ┆ 0.67     │
│ HMM             ┆ 0.97          ┆ 0.7             ┆ 0.933333        ┆ 0.985714        ┆ 0.63     │
│ LL              ┆ 0.83          ┆ 0.53            ┆ 0.765957        ┆ 0.886792        ┆ 0.28     │
└─────────────────┴───────────────┴─────────────────┴─────────────────┴─────────────────┴──────────┘

-> In Human Groups (see Group Problem Solving) there is the tendency that the smarter the group, the more it is a "Truth Supported" Decision Scheme, the "dumber" the group, the more it is "proportional"

### Correlation for groups (ignoring 1 member, as it is always 1)

In [17]:
print("Pearson Correlation:")
print(
    unanimity.filter(pl.col("group_constellation").str.len_chars() > 1)
    .select(pl.exclude("group_constellation"))
    .corr()
)

print("Spearman Rank Correlation:")

print(
    unanimity.filter(pl.col("group_constellation").str.len_chars() > 1)
    .select(pl.exclude("group_constellation"))
    .with_columns(pl.all().rank())
    .corr()
)

Pearson Correlation:
shape: (5, 5)
┌───────────────┬─────────────────┬─────────────────────┬───────────────────────┬──────────┐
│ End unanimity ┆ Start unanimity ┆ End Unanimity | not ┆ End Unanimity | Start ┆ accuracy │
│ ---           ┆ ---             ┆ Start Unan…         ┆ Unanimit…             ┆ ---      │
│ f64           ┆ f64             ┆ ---                 ┆ ---                   ┆ f64      │
│               ┆                 ┆ f64                 ┆ f64                   ┆          │
╞═══════════════╪═════════════════╪═════════════════════╪═══════════════════════╪══════════╡
│ 1.0           ┆ 0.84163         ┆ 0.958687            ┆ 0.537227              ┆ 0.527037 │
│ 0.84163       ┆ 1.0             ┆ 0.745945            ┆ 0.369057              ┆ 0.37374  │
│ 0.958687      ┆ 0.745945        ┆ 1.0                 ┆ 0.423489              ┆ 0.48994  │
│ 0.537227      ┆ 0.369057        ┆ 0.423489            ┆ 1.0                   ┆ 0.513904 │
│ 0.527037      ┆ 0.37374         ┆ 0.48994             ┆ 0.513904              ┆ 1.0      │
└───────────────┴─────────────────┴─────────────────────┴───────────────────────┴──────────┘
Spearman Rank Correlation:
shape: (5, 5)
┌───────────────┬─────────────────┬─────────────────────┬───────────────────────┬──────────┐
│ End unanimity ┆ Start unanimity ┆ End Unanimity | not ┆ End Unanimity | Start ┆ accuracy │
│ ---           ┆ ---             ┆ Start Unan…         ┆ Unanimit…             ┆ ---      │
│ f64           ┆ f64             ┆ ---                 ┆ ---                   ┆ f64      │
│               ┆                 ┆ f64                 ┆ f64                   ┆          │
╞═══════════════╪═════════════════╪═════════════════════╪═══════════════════════╪══════════╡
│ 1.0           ┆ 0.866815        ┆ 0.931826            ┆ 0.515492              ┆ 0.631664 │
│ 0.866815      ┆ 1.0             ┆ 0.754515            ┆ 0.24823               ┆ 0.437494 │
│ 0.931826      ┆ 0.754515        ┆ 1.0                 ┆ 0.378325              ┆ 0.630809 │
│ 0.515492      ┆ 0.24823         ┆ 0.378325            ┆ 1.0                   ┆ 0.478076 │
│ 0.631664      ┆ 0.437494        ┆ 0.630809            ┆ 0.478076              ┆ 1.0      │
└───────────────┴─────────────────┴─────────────────────┴───────────────────────┴──────────┘

-> significantly correlated

---
-> Accuracy Correlates with Unanimity
Of course this could be that if everyone is correct in the beginning, then if they that way, then the chance of being correct is higher,
But can we increase the accuracy by accepting when a group starts with one answer?

## Analysis: Is the group finding answers "together" ? (e.g. can it find answers out of wrong start)

In [18]:
correctness_influence = (
    mad_analysis.with_columns(
        correct_before=comparer(
            pl.col(AnalysisColumn.parsed_combined_answers_before.value),
            pl.col("answer_string"),
        )
    )
    .group_by("group_constellation")
    .agg(
        pl.when(pl.col("correct_before"))
        .then(pl.col("is_correct"))
        .otherwise(None)
        .mean()
        .alias("Correct | Correct in Beginning"),
        pl.when(pl.col("correct_before"))
        .then(None)
        .otherwise(pl.col("is_correct"))
        .mean()
        .alias("Correct | !Correct in Beginning"),
        accuracy=pl.col("is_correct").mean(),
    )
)

correctness_influence

shape: (34, 4)
┌─────────────────────┬────────────────────────────────┬───────────────────────┬──────────┐
│ group_constellation ┆ Correct | Correct in Beginning ┆ Correct | !Correct in ┆ accuracy │
│ ---                 ┆ ---                            ┆ Beginnin…             ┆ ---      │
│ str                 ┆ f64                            ┆ ---                   ┆ f64      │
│                     ┆                                ┆ f64                   ┆          │
╞═════════════════════╪════════════════════════════════╪═══════════════════════╪══════════╡
│ HHHH                ┆ 0.971429                       ┆ 0.066667              ┆ 0.7      │
│ H                   ┆ 0.986111                       ┆ 0.142857              ┆ 0.75     │
│ L                   ┆ 0.714286                       ┆ 0.101266              ┆ 0.23     │
│ LLLL                ┆ 0.655172                       ┆ 0.098592              ┆ 0.26     │
│ LLL                 ┆ 0.774194                       ┆ 0.188406              ┆ 0.37     │
│ …                   ┆ …                              ┆ …                     ┆ …        │
│ LMM                 ┆ 1.0                            ┆ 0.121951              ┆ 0.64     │
│ LMMM                ┆ 0.933333                       ┆ 0.125                 ┆ 0.61     │
│ HHH                 ┆ 0.972222                       ┆ 0.142857              ┆ 0.74     │
│ HHL                 ┆ 0.907692                       ┆ 0.171429              ┆ 0.65     │
│ HL                  ┆ 0.918919                       ┆ 0.301587              ┆ 0.53     │
└─────────────────────┴────────────────────────────────┴───────────────────────┴──────────┘

While the difference in Correct | Correct in Beginning is negligible, the true power lies in changing the answer when They are not correct.

In [19]:
(
    correctness_influence.join(unanimity, how="left", on="group_constellation")
    .filter(pl.col("group_constellation").str.len_chars() > 1)
    .select(pl.exclude("group_constellation"))
    .with_columns(pl.all().rank())
    .corr()
)

shape: (8, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ Correct |  ┆ Correct |  ┆ accuracy  ┆ End        ┆ Start     ┆ End       ┆ End       ┆ accuracy_ │
│ Correct in ┆ !Correct   ┆ ---       ┆ unanimity  ┆ unanimity ┆ Unanimity ┆ Unanimity ┆ right     │
│ Beginning  ┆ in         ┆ f64       ┆ ---        ┆ ---       ┆ | not     ┆ | Start   ┆ ---       │
│ ---        ┆ Beginnin…  ┆           ┆ f64        ┆ f64       ┆ Start     ┆ Unanimit… ┆ f64       │
│ f64        ┆ ---        ┆           ┆            ┆           ┆ Unan…     ┆ ---       ┆           │
│            ┆ f64        ┆           ┆            ┆           ┆ ---       ┆ f64       ┆           │
│            ┆            ┆           ┆            ┆           ┆ f64       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0        ┆ -0.14882   ┆ 0.76005   ┆ 0.653338   ┆ 0.481993  ┆ 0.681992  ┆ 0.393411  ┆ 0.76005   │
│ -0.14882   ┆ 1.0        ┆ -0.208889 ┆ -0.415312  ┆ -0.407628 ┆ -0.320593 ┆ -0.175008 ┆ -0.208889 │
│ 0.76005    ┆ -0.208889  ┆ 1.0       ┆ 0.631664   ┆ 0.437494  ┆ 0.630809  ┆ 0.478076  ┆ 1.0       │
│ 0.653338   ┆ -0.415312  ┆ 0.631664  ┆ 1.0        ┆ 0.866815  ┆ 0.931826  ┆ 0.515492  ┆ 0.631664  │
│ 0.481993   ┆ -0.407628  ┆ 0.437494  ┆ 0.866815   ┆ 1.0       ┆ 0.754515  ┆ 0.24823   ┆ 0.437494  │
│ 0.681992   ┆ -0.320593  ┆ 0.630809  ┆ 0.931826   ┆ 0.754515  ┆ 1.0       ┆ 0.378325  ┆ 0.630809  │
│ 0.393411   ┆ -0.175008  ┆ 0.478076  ┆ 0.515492   ┆ 0.24823   ┆ 0.378325  ┆ 1.0       ┆ 0.478076  │
│ 0.76005    ┆ -0.208889  ┆ 1.0       ┆ 0.631664   ┆ 0.437494  ┆ 0.630809  ┆ 0.478076  ┆ 1.0       │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

## Influence of Group Aggregation Protocol

In [20]:
group_reply_influence_table = pl.DataFrame(
    {
        "group_constellation": mad_analysis["group_constellation"]
        .unique()
        .extend(baseline_frame_with_group_constellation["group_constellation"].unique())
        .sort()
    }
)

for strategy in [MajorityVote(), SingularityVote()]:
    new_group_reply_agg = GroupReplyAggregator(strategy)
    group_reply_influence_table = group_reply_influence_table.join(
        apply_parsing_and_group_decision(
            mad_frame, parser, comparer, new_group_reply_agg
        )
        .with_columns(make_group_constellation())
        .group_by("group_constellation")
        .agg(accuracy=pl.col("is_correct").mean())
        .select(
            "group_constellation",
            pl.col("accuracy").alias(f"Accuracy ({strategy.__class__.__name__})"),
        ),
        on="group_constellation",
        how="inner",
    )

group_reply_influence_table = group_reply_influence_table.with_columns(
    deviation=(
        pl.max_horizontal(pl.exclude("group_constellation"))
        - pl.min_horizontal(pl.exclude("group_constellation"))
    ).alias("range")
)

group_reply_influence_table

shape: (34, 4)
┌─────────────────────┬─────────────────────────┬────────────────────────────┬───────────┐
│ group_constellation ┆ Accuracy (MajorityVote) ┆ Accuracy (SingularityVote) ┆ deviation │
│ ---                 ┆ ---                     ┆ ---                        ┆ ---       │
│ str                 ┆ f64                     ┆ f64                        ┆ f64       │
╞═════════════════════╪═════════════════════════╪════════════════════════════╪═══════════╡
│ HH                  ┆ 0.77                    ┆ 0.75                       ┆ 0.02      │
│ MMM                 ┆ 0.58                    ┆ 0.57                       ┆ 0.01      │
│ HHH                 ┆ 0.74                    ┆ 0.71                       ┆ 0.03      │
│ HLL                 ┆ 0.46                    ┆ 0.32                       ┆ 0.14      │
│ LMM                 ┆ 0.64                    ┆ 0.59                       ┆ 0.05      │
│ …                   ┆ …                       ┆ …                          ┆ …         │
│ LLM                 ┆ 0.56                    ┆ 0.49                       ┆ 0.07      │
│ HL                  ┆ 0.53                    ┆ 0.5                        ┆ 0.03      │
│ HHMM                ┆ 0.61                    ┆ 0.58                       ┆ 0.03      │
│ HHM                 ┆ 0.7                     ┆ 0.67                       ┆ 0.03      │
│ HMM                 ┆ 0.63                    ┆ 0.62                       ┆ 0.01      │
└─────────────────────┴─────────────────────────┴────────────────────────────┴───────────┘

In [21]:
group_reply_influence_table.drop("group_constellation").with_columns(
    pl.all().rank()
).corr()

shape: (3, 3)
┌─────────────────────────┬────────────────────────────┬───────────┐
│ Accuracy (MajorityVote) ┆ Accuracy (SingularityVote) ┆ deviation │
│ ---                     ┆ ---                        ┆ ---       │
│ f64                     ┆ f64                        ┆ f64       │
╞═════════════════════════╪════════════════════════════╪═══════════╡
│ 1.0                     ┆ 0.939654                   ┆ -0.052763 │
│ 0.939654                ┆ 1.0                        ┆ -0.293191 │
│ -0.052763               ┆ -0.293191                  ┆ 1.0       │
└─────────────────────────┴────────────────────────────┴───────────┘

-> Slightly Negative Correlation between Accuracy and the deviation, meaning the better the more MajorityVote == SingularityVote -> Same argument as before

## Inter-Model Correctness Correlation (Aka answer diversity)

In [22]:
mad_analysis

shape: (3_400, 23)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id    ┆ run_id ┆ question_i ┆ phoenix_sp ┆ … ┆ ___parsed_ ┆ ___parsed_ ┆ is_correct ┆ group_cons │
│ ---   ┆ ---    ┆ d          ┆ an_id      ┆   ┆ combined_a ┆ combined_a ┆ ---        ┆ tellation  │
│ i64   ┆ i64    ┆ ---        ┆ ---        ┆   ┆ nswers_bef ┆ nswers_aft ┆ bool       ┆ ---        │
│       ┆        ┆ i64        ┆ str        ┆   ┆ …          ┆ …          ┆            ┆ str        │
│       ┆        ┆            ┆            ┆   ┆ ---        ┆ ---        ┆            ┆            │
│       ┆        ┆            ┆            ┆   ┆ str        ┆ str        ┆            ┆            │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 3260  ┆ 43     ┆ 5          ┆ 1aa14e4c91 ┆ … ┆ J          ┆ J          ┆ true       ┆ H          │
│       ┆        ┆            ┆ 5cb1a3     ┆   ┆            ┆            ┆            ┆            │
│ 3261  ┆ 43     ┆ 6          ┆ c0ea9a6816 ┆ … ┆ I          ┆ I          ┆ true       ┆ H          │
│       ┆        ┆            ┆ 5ac33e     ┆   ┆            ┆            ┆            ┆            │
│ 3262  ┆ 43     ┆ 0          ┆ 6bc64c3c96 ┆ … ┆ G          ┆ G          ┆ true       ┆ H          │
│       ┆        ┆            ┆ 1beda7     ┆   ┆            ┆            ┆            ┆            │
│ 3263  ┆ 43     ┆ 8          ┆ 35ee808025 ┆ … ┆ C          ┆ C          ┆ false      ┆ H          │
│       ┆        ┆            ┆ 489b27     ┆   ┆            ┆            ┆            ┆            │
│ 3264  ┆ 43     ┆ 2          ┆ ee9c12870a ┆ … ┆ F          ┆ F          ┆ true       ┆ H          │
│       ┆        ┆            ┆ 3b979e     ┆   ┆            ┆            ┆            ┆            │
│ …     ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 34855 ┆ 352    ┆ 68         ┆ fd114d6a38 ┆ … ┆ I          ┆ I          ┆ true       ┆ HLM        │
│       ┆        ┆            ┆ 99064b     ┆   ┆            ┆            ┆            ┆            │
│ 34856 ┆ 352    ┆ 141        ┆ 30a0911e0e ┆ … ┆ F          ┆ F          ┆ true       ┆ HLM        │
│       ┆        ┆            ┆ fbd5dd     ┆   ┆            ┆            ┆            ┆            │
│ 34857 ┆ 352    ┆ 27         ┆ dc23bc8eef ┆ … ┆ ___all_vot ┆ E          ┆ true       ┆ HLM        │
│       ┆        ┆            ┆ 8f7788     ┆   ┆ es_invalid ┆            ┆            ┆            │
│       ┆        ┆            ┆            ┆   ┆ ___        ┆            ┆            ┆            │
│ 34858 ┆ 352    ┆ 79         ┆ e50f91de53 ┆ … ┆ ___differe ┆ E          ┆ false      ┆ HLM        │
│       ┆        ┆            ┆ b869cb     ┆   ┆ nt_votes__ ┆            ┆            ┆            │
│       ┆        ┆            ┆            ┆   ┆ _          ┆            ┆            ┆            │
│ 34859 ┆ 352    ┆ 142        ┆ 94e15af76b ┆ … ┆ E          ┆ E          ┆ true       ┆ HLM        │
│       ┆        ┆            ┆ a6017c     ┆   ┆            ┆            ┆            ┆            │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

#### For Individual answers

In [23]:
individual_models_answer_per_question = (
    (
        baseline_frame.with_columns(
            parser(pl.col("final_answer")).alias(AnalysisColumn.parsed_answer.value)
        )
        .with_columns(
            pl.col("model_name").replace(MODEL_NAME_TO_LETTER_MAPPING),
            is_correct=comparer(
                pl.col(AnalysisColumn.parsed_answer.value), pl.col("answer_string")
            ),
        )
        .pivot(
            values="is_correct",
            index="question_id",
            on="model_name",
            aggregate_function="mean",
        )
    )
    .sort("question_id")
    .select("question_id", "L", "M", "H")
    .with_columns(pl.exclude("question_id").cast(bool))
)

individual_models_answer_per_question

shape: (100, 4)
┌─────────────┬───────┬───────┬───────┐
│ question_id ┆ L     ┆ M     ┆ H     │
│ ---         ┆ ---   ┆ ---   ┆ ---   │
│ i64         ┆ bool  ┆ bool  ┆ bool  │
╞═════════════╪═══════╪═══════╪═══════╡
│ 0           ┆ false ┆ true  ┆ true  │
│ 1           ┆ false ┆ false ┆ true  │
│ 2           ┆ false ┆ false ┆ true  │
│ 3           ┆ false ┆ true  ┆ false │
│ 4           ┆ false ┆ false ┆ true  │
│ …           ┆ …     ┆ …     ┆ …     │
│ 155         ┆ true  ┆ true  ┆ true  │
│ 156         ┆ true  ┆ true  ┆ false │
│ 157         ┆ true  ┆ true  ┆ true  │
│ 158         ┆ true  ┆ true  ┆ true  │
│ 159         ┆ false ┆ false ┆ false │
└─────────────┴───────┴───────┴───────┘

In [24]:
individual_models_answer_per_question.drop("question_id").corr()

shape: (3, 3)
┌──────────┬──────────┬──────────┐
│ L        ┆ M        ┆ H        │
│ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ 1.0      ┆ 0.313313 ┆ 0.2446   │
│ 0.313313 ┆ 1.0      ┆ 0.603185 │
│ 0.2446   ┆ 0.603185 ┆ 1.0      │
└──────────┴──────────┴──────────┘

--> Actually surprisingly different

In [25]:
df = pl.concat(
    [
        individual_models_answer_per_question.group_by(col)
        .agg(pl.all().exclude(col, "question_id").mean())
        .with_columns(
            pl.when(pl.col(col))
            .then(pl.lit(col + "_correct"))
            .otherwise(pl.lit(col + "_incorrect"))
            .alias("Given"),
            pl.when(pl.col(col)).then(pl.lit(1.0)).otherwise(pl.lit(0.0)).alias(col),
        )
        for col in individual_models_answer_per_question.columns
        if col != "question_id"
    ],
    how="diagonal",
)

df_single = df.select("Given", "L", "M", "H")

df_single

shape: (6, 4)
┌─────────────┬──────────┬──────────┬──────────┐
│ Given       ┆ L        ┆ M        ┆ H        │
│ ---         ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪══════════╪══════════╡
│ L_incorrect ┆ 0.0      ┆ 0.476923 ┆ 0.553846 │
│ L_correct   ┆ 1.0      ┆ 0.8      ┆ 0.8      │
│ M_incorrect ┆ 0.170732 ┆ 0.0      ┆ 0.292683 │
│ M_correct   ┆ 0.474576 ┆ 1.0      ┆ 0.881356 │
│ H_incorrect ┆ 0.194444 ┆ 0.194444 ┆ 0.0      │
│ H_correct   ┆ 0.4375   ┆ 0.8125   ┆ 1.0      │
└─────────────┴──────────┴──────────┴──────────┘

-> They are not completely overlapping in the single answer case.

This means could be some diversity effect going on

---

In [26]:
individual_groups_answer_per_question = (
    (
        mad_analysis.filter(pl.col("group_constellation").str.len_chars() == 1).pivot(
            values="is_correct",
            index="question_id",
            on="group_constellation",
            aggregate_function="mean",
        )
    )
    .sort("question_id")
    .with_columns(pl.exclude("question_id").cast(bool))
)

df_single_mad = pl.concat(
    [
        individual_groups_answer_per_question.group_by(col)
        .agg(pl.all().exclude(col, "question_id").mean())
        .with_columns(
            pl.when(pl.col(col))
            .then(pl.lit(col + "_correct"))
            .otherwise(pl.lit(col + "_incorrect"))
            .alias("Given"),
            pl.when(pl.col(col)).then(pl.lit(1.0)).otherwise(pl.lit(0.0)).alias(col),
        )
        for col in individual_models_answer_per_question.columns
        if col != "question_id"
    ],
    how="diagonal",
).select("Given", "L", "M", "H")

df_single_mad

shape: (6, 4)
┌─────────────┬──────────┬──────────┬──────────┐
│ Given       ┆ L        ┆ M        ┆ H        │
│ ---         ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪══════════╪══════════╡
│ L_incorrect ┆ 0.0      ┆ 0.454545 ┆ 0.688312 │
│ L_correct   ┆ 1.0      ┆ 0.869565 ┆ 0.956522 │
│ M_incorrect ┆ 0.066667 ┆ 0.0      ┆ 0.466667 │
│ M_correct   ┆ 0.363636 ┆ 1.0      ┆ 0.981818 │
│ H_correct   ┆ 0.293333 ┆ 0.72     ┆ 1.0      │
│ H_incorrect ┆ 0.04     ┆ 0.04     ┆ 0.0      │
└─────────────┴──────────┴──────────┴──────────┘

In [27]:
combined_ind = individual_models_answer_per_question.join(
    individual_groups_answer_per_question, on="question_id", suffix="_mad"
)
pl.concat(
    [
        combined_ind.group_by(col)
        .agg(pl.all().exclude(col, "question_id").mean())
        .with_columns(
            pl.when(pl.col(col))
            .then(pl.lit(col + "_correct"))
            .otherwise(pl.lit(col + "_incorrect"))
            .alias("Given"),
            pl.when(pl.col(col)).then(pl.lit(1.0)).otherwise(pl.lit(0.0)).alias(col),
        )
        for col in combined_ind.columns
        if col != "question_id"
    ],
    how="diagonal",
).select("Given", pl.exclude("Given"))

shape: (12, 7)
┌─────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Given           ┆ L        ┆ M        ┆ H        ┆ H_mad    ┆ M_mad    ┆ L_mad    │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str             ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ L_correct       ┆ 1.0      ┆ 0.8      ┆ 0.8      ┆ 0.857143 ┆ 0.771429 ┆ 0.514286 │
│ L_incorrect     ┆ 0.0      ┆ 0.476923 ┆ 0.553846 ┆ 0.692308 ┆ 0.430769 ┆ 0.076923 │
│ M_incorrect     ┆ 0.170732 ┆ 0.0      ┆ 0.292683 ┆ 0.487805 ┆ 0.146341 ┆ 0.02439  │
│ M_correct       ┆ 0.474576 ┆ 1.0      ┆ 0.881356 ┆ 0.932203 ┆ 0.830508 ┆ 0.372881 │
│ H_correct       ┆ 0.4375   ┆ 0.8125   ┆ 1.0      ┆ 0.9375   ┆ 0.734375 ┆ 0.3125   │
│ …               ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        │
│ H_mad_correct   ┆ 0.4      ┆ 0.733333 ┆ 0.8      ┆ 1.0      ┆ 0.72     ┆ 0.293333 │
│ M_mad_incorrect ┆ 0.177778 ┆ 0.222222 ┆ 0.377778 ┆ 0.466667 ┆ 0.0      ┆ 0.066667 │
│ M_mad_correct   ┆ 0.490909 ┆ 0.890909 ┆ 0.854545 ┆ 0.981818 ┆ 1.0      ┆ 0.363636 │
│ L_mad_correct   ┆ 0.782609 ┆ 0.956522 ┆ 0.869565 ┆ 0.956522 ┆ 0.869565 ┆ 1.0      │
│ L_mad_incorrect ┆ 0.220779 ┆ 0.480519 ┆ 0.571429 ┆ 0.688312 ┆ 0.454545 ┆ 0.0      │
└─────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

> See Obsidian

#### Is the "nobody is right case" in HHH actually unanimous?

In [28]:
print("Answers where everyone was wrong:")

everyone_wrong = (
    mad_analysis.filter(pl.col("group_constellation") == "HHH")
    .explode(AnalysisColumn.parsed_individual_answers_before.value)
    .with_columns(
        is_individually_correct=comparer(
            pl.col(AnalysisColumn.parsed_individual_answers_before.value),
            pl.col("answer_string"),
        )
    )
    .group_by("question_id")
    .agg(
        number_wrong=pl.len(),
        answers=pl.col(AnalysisColumn.parsed_individual_answers_before.value).implode(),
        is_individually_correct=pl.col("is_individually_correct").implode(),
    )
    .filter(pl.col("is_individually_correct").list.eval(pl.element().not_()).list.all())
    .drop("number_wrong", "is_individually_correct")
)

print(everyone_wrong)
unanimous = (
    everyone_wrong["answers"]
    .filter(everyone_wrong["answers"].list.n_unique() == 1)
    .count()
)
print(f"Of that unanimous: {unanimous}")
print("Contentious:")
print(everyone_wrong["answers"].filter(everyone_wrong["answers"].list.n_unique() != 1))

Answers where everyone was wrong:
shape: (23, 2)
┌─────────────┬─────────────────────────────────┐
│ question_id ┆ answers                         │
│ ---         ┆ ---                             │
│ i64         ┆ list[str]                       │
╞═════════════╪═════════════════════════════════╡
│ 15          ┆ ["A", "A", "A"]                 │
│ 125         ┆ ["___not_parsable___", "___not… │
│ 124         ┆ ["A", "A", "A"]                 │
│ 62          ┆ ["C", "D", "C"]                 │
│ 7           ┆ ["A", "A", "A"]                 │
│ …           ┆ …                               │
│ 12          ┆ ["D", "D", "D"]                 │
│ 121         ┆ ["___not_parsable___", "I", "_… │
│ 149         ┆ ["B", "___not_parsable___", "B… │
│ 3           ┆ ["D", "D", "D"]                 │
│ 79          ┆ ["C", "C", "C"]                 │
└─────────────┴─────────────────────────────────┘
Of that unanimous: 15
Contentious:
shape: (8,)
Series: 'answers' [list[str]]
[
	["C", "D", "C"]
	["E", "A", "___not_parsable___"]
	["D", "E", "E"]
	["___not_parsable___", "F", "___not_parsable___"]
	["C", "___not_parsable___", "___not_parsable___"]
	["D", "H", "D"]
	["___not_parsable___", "I", "___not_parsable___"]
	["B", "___not_parsable___", "B"]
]

C# Intra-Group Correctness Correlation (Aka group diversity)

C# Intra-Group Correctness Correlation (Aka group diversity)